src/services/upload/queueProcessor.ts

The queue process processes the queue using a loop which run until there is no item in the queue...
This is an update from the previous method that used recursive calls.
But while updating the logic....A mistake was made which caused it to still process the queue in recursive way. [1]
this is a fix for that
Plus a few other changes
1. export the `RequestCanceller` interface as it is needed outside the class too
2. removing the type string from response as it can be of any type 
3. corrected the type of request to `request: (canceller?: RequestCanceller) => Promise<T>`
[1] https://github.com/ente-io/bada-frame/pull/144/files#diff-58cf8feffce2897b48555b3ae553f2f3d58fb9da4633da9aefb7d0bdd9abd274L63

Fix queue processor

---

src/services/upload/metadataService.ts

The get exif data returns null or undefined when exif parsing fails. The destructing of null repsonse was causing property not found in the object error.
Also video files exif was tried to be extracted which would definetely cause exif reading failure. Added a check for only image file before getExif call
This two bugs has been fixed
- Test with a image with exif
- Test with image that doesn't have exif
- Test with video file

exif data can be null so dont destruction function response

---

src/components/PhotoFrame.tsx

`autoSizer`- react -window component for width and height detection and passing to react window)
The width of the wrapping container  of the `autoSizer`   set to auto , whereas the autoSizer sets the width for react window.
the change of width for the container is quicker than the change in value of the `autoSizer` width and height property. which tab width is changed.
So, when the width of the tab decreases then the `autoSizer` would take some time to follow and for that time the `autoSizer` was bigger than the container which caused the content to overflow and then a scrollbar to appear.
because of the scrollbar, the width of the viewport is futhur decreased which triggered another decrease event for `autoSizer`.
But when the `autoSizer` reached that , width the content is now the size …

fix looped resize

---

src/components/PhotoFrame.tsx
src/components/pages/gallery/Collections.tsx
src/pages/gallery/index.tsx
src/utils/collection/index.ts

Updates the selection behavior of the app . Now when a file of other collection is selected then the previous selected files are cleared.
But the selection is NOT cleared for just moving between collections
Also, selected Items and selectedOptions are now only shown as selected in the collection you selected it and not in `All`

Update selection behaviour

---

src/components/pages/gallery/Collections.tsx

The all section doesn't have a `collectionID` ,so currently  the active collection was set to undefined, when user navigated to all, setting it 0 as a better identifiable value which can be use for detecting the user is in all section

set active collection to 0 for all section 

---

src/components/PhotoFrame.tsx
src/components/PhotoSwipe/PhotoSwipe.tsx
src/components/pages/gallery/CollectionSelector.tsx
src/pages/gallery/index.tsx
src/services/collectionService.ts
src/services/fileService.ts
src/utils/collection/index.ts
src/utils/file/index.ts

Disable selecting (thereby add and move operation) and favorite button when user open shared Collection files
hides shared collection file from all section

Disable shared collection ops

---

src/pages/gallery/index.tsx
src/services/collectionService.ts

Refreshing in between a sync was causing sync to stop.
Fix
1. Collection updation should be updated after collection have been successfully persisted.
2. don't remove empty collection from local as they may be unsynced collections

Fix refresh stop sync

---

src/pages/gallery/index.tsx
src/utils/collection/index.ts

Changes 
- moved the syncing after add or move to collection logic to gallery helper functions
- moved logic which should occur even on failure (like selected file being unselecting and loading complete) to finally block to guarantee their execution
We can decide if we want to deselect selected files if the operation fails as the user may want to reattempt them and would have to re-select if we clear.
Tested by blocking network calls for a specific request and seeing the behavior.

Handle failure

---

src/pages/gallery/index.tsx
src/services/collectionService.ts

Doing this because...collections are synced before files so...while files are synced their can be collections which don't have
any file in it and it would trigger a false error.

dont log collections missing from collectionsAndTheirLatestFile list

---

src/pages/gallery/index.tsx

Fixes vishnu's bhaiya's reported bug. Where gallery is stuck in infinite load
- open `<URL>/gallery` directly causes the app to go into infinite load

fix too many location/history api request

---

src/components/PhotoFrame.tsx
src/components/PhotoSwipe/PhotoSwipe.tsx
src/pages/_app.tsx
src/utils/file/index.ts
src/utils/photoFrame/index.ts

Better UI for when playback failed for a file.
Earlier option didn't remain there when user closed and reopened the video
earlier state if user closes and reopens a unplayable video
new UI

Better playback failed dialog

---

src/components/FixLargeThumbnail.tsx
src/utils/strings/englishConstants.tsx

Adds a new UI state -` NOOP`, this is set when the user doesn't has any thumbnails to migrate.
the `COMPLETED`, state was shown earlier which would now be shown after successful migration and stay till the user closes the migrate dailog after which the state would change to `NOOP` if no large thumbnail files are found or to `NOT_STARTED` again if files were missed during last migrate

add new NOOP state to migrateThumbnail

---

src/services/migrateThumbnailService.ts

missed trashFiles thumbnail migration earlier , adds that

migrate trashFiles thumbnail too

---

src/services/fileService.ts
src/services/trashService.ts
src/services/upload/uploadManager.ts
src/utils/file/index.ts

Files that was used to set LocalDB  was passed by reference(shallow copy)  to the component State   so , when photoSwipe added its required property , it got passed to the original File and was saved in localDB
passed a deep copy of the Files , so that the original files array is not updated.
happened while adding updateCreationTime feature.
[Commit](https://github.com/ente-io/bada-frame/pull/212/commits/7444ad183ea7006b48abaafbd9221049bf47999b) fixing the issue
Other things are just refactoring code

Fix objectURL set in local db

---

src/services/fileService.ts

collections sort by latest file broken 
because of a previous change #212, the returned files were no longer sorted and the getLatestCollectionFiles function broke as it expected sorted file list
update the files array so that returned files  from the function  is sorted as the caller expect sorted files and use spread operator so that a deep copy of the file is used to set the state to avoid the #212 problem

fix collection sort by latest files

---

src/services/upload/thumbnailService.ts

updated info object key from `type`  to `fileFormat` , as sentry does not recognise `type` as a valid  property name for some reason
tested locally by reproducing error in staging and see logged error on sentry

fix file type not logged on image thumbnail generation fail

---

src/components/PhotoSwipe/PhotoSwipe.tsx

if the user didn't select a a different time and clicked on save the button didn't work.
Fixes to just close and don't call update metadata in that case
saving with same name after edit works

simply close date edit if saved without edit

---

src/components/pages/gallery/Upload.tsx

fix the sorting of files paths  so that are sorted in  hierarchical order. and so the first and last folder check we make to find multiple folder detection works.
For Example 
let the  files be  a, b/1, c/2, z  (b/1 mean a file named 1 inside a folder b)
current sorted order
a
b/1
c/2
z
the current sorting is based on string comparison of path and so that first and last would both be in root directory and hence multiple folder wont be detected.
but the correct sorting is according number of slashes in name
a
z
b/1
c/2
and now the first first is in root directory but the last one is in c directory and so multiple folder option will be triggered
tested by the test case folder structure

Fix multi folder detection

---

src/pages/_app.tsx
src/pages/credentials/index.tsx
src/pages/gallery/index.tsx
src/services/billingService.ts
src/utils/billingUtil.ts
src/utils/storage/localStorage.ts

The session storage variable were cleared when user was redirected to payments.ente.io. [ new behaviour...have tested earlier the key was not cleared that time]
So when user was redirected back to web.ente.io he didn't have the key and was redirectly to credentials page but the query params were not preserved during auth redirect. so the success and failure info was lost.
Fix
saved the redirect url in (~localDB~ appContext)  before redirecting the user for auth and used that to redirect from credentials page....so the queryParam are preserved and parsed when user comes back to gallery and the message is shown
tested by trying to make a payment then pressed back button on the payments page

Stripe redirect fix

---

src/services/ffmpegService.ts

clear failed `ffmpeg` instance on load fail, so that new load is triggered
tested by blocking ffmpeg request for console a file  and then without refreshing making the page making upload....
this triggired refetching as expected.

ffmpeg load fail handling

---

src/components/PhotoFrame.tsx
src/components/pages/gallery/PreviewCard.tsx
src/services/downloadManager.ts
src/services/migrateThumbnailService.ts
src/services/upload/thumbnailService.ts
src/utils/file/index.ts

- store file that are converted for preview with `_converted` suffixed key instead of `forPreview` attribute as some file don't need conversion and hence same file can be use for for-preview and download and are unnecessarily re-downloaded 
-  fix thumbnail in-memory cache not used

Download manager improvements

---

src/services/upload/exifService.ts

fixes https://sentry.ente.io/organizations/ente/issues/2030/?project=2&referrer=webhooks_plugin
- add fail safe try catch block in getExifData function, to prevent upload failure if anything fails in exif parsing
- add error logging to getUnixTime fail to know what value it failed on, as ideally it should not have ... Indicating that the exif parsing is maybe not respecting the API contract and sending time in some other format than `Date`
- simulated getUnixTime fail and confirmed that upload doesn't fail on its failure

fix getUnixTime failure Error handling

---

src/services/exportService.ts

`this.ElectronAPIs` is `null` on web , so trying to access exists property on it threw the error
web app loading  after change

fix allElectronAPIsExist intialisation

---

src/components/pages/gallery/Upload.tsx

fixes choice modal (to select whether the user wants to upload folders as separate or as one ) not showing up when two sibling folders are uploaded with no common ancestor folder.
tested by dropping two folders 
`/image`
`/video`
choice modal comes up

fix multiple folder upload choices not showing up for sibling folder with no common ancestor

---

configUtil.js
next.config.js
sentry.client.config.js
sentry.server.config.js
sentryConfigUtil.js
src/constants/sentry/index.ts

sentry release uploads were done even when the test build was done locally. 
disabling  releases on local builds
also refactored sentry constants 
tested locally  that release is not made when sentry env is development

disable sentry release cli for local build

---

configUtil.js
next.config.js
sentry.client.config.js
sentry.server.config.js
sentryConfigUtil.js
src/constants/sentry/index.ts

- renamed `isSentryEnabled` to `getIsSentryEnabled`
- renamed `SENTRY_ENABLED` and `ENABLED` to `SENTRY_IS_ENABLED` and `IS_ENABLED` respectively 
- automatic  sentry dry running  in hot reload stopped working when the `dryRun` was explicitly set so, use `next`  phase  to detect if the dev server is running and disable sentry release 
tested app building 
tested that sentry is dry running in dev server phase even if sentry enabled

Rename sentry variables

---

src/services/upload/readFileService.ts

earlier logic was not removing the `-edited` suffix correctly 😢 
it checked for the suffix but didn't take into account the extensions 
tested by trying to upload files with `-edited` sufficed files

fix getFileOriginalName logic

---

src/services/exportService.ts
src/services/ffmpegService.ts
src/services/migrateThumbnailService.ts
src/services/updateCreationTimeWithExif.ts
src/services/upload/exifService.ts
src/services/upload/metadataService.ts
src/services/upload/readFileService.ts
src/services/upload/thumbnailService.ts
src/services/upload/uploadManager.ts
src/services/upload/uploadService.ts
src/services/upload/uploader.ts
src/utils/file/index.ts
src/worker/crypto.worker.js

^title
have moved file reader logic to worker once to check if it helps with reducing crashes but it didn't help.
so reverting that change and moving back to the earlier logic of reusing file Readers as much as possible.
the app is building successfully, so no imports are broken.
tested flows
- upload with the complete list of sample files
- export

reuse file readers

---

src/components/PhotoFrame.tsx

fixes  https://sentry.ente.io/organizations/ente/issues/2338/ 
by adding check that `rangeStart` is not undefined before executing range select
and fixes selecting two items using range select by correctly checking used to find if all items in the range are selected.
tested locally the changes

fixes range-select errors

---

src/components/pages/gallery/PlanSelector.tsx
src/pages/gallery/index.tsx
src/types/gallery/index.ts
src/utils/strings/englishConstants.tsx

handle `getPlans` failure better.
- catch the error and log
- open a dialog with option to re-open the plans modal again
tested by throwing an error after getPlans API call

handle plan modal opening error better

---

src/services/trashService.ts

return `currentTrash` array if getTrash fails to avoid `updatedTrash` is undefined errors
tested locally

return empty array if updateTrash fails

---

yarn.lock

fixes https://github.com/ente-io/bada-frame/security/dependabot/yarn.lock/node-fetch/open
- https://github.com/vercel/next.js/compare/v11.1.3...v11.1.4
building successfully

bump next from 11.1.3 to 11.1.4.

---

src/services/queueProcessor.ts

it was processing only one request at a time even if `maxParallelProcesses` was sent more than 1
tested locally

fix queue processor 

---

src/components/PhotoFrame.tsx
src/pages/index.tsx

adds logic do ^title
makes mobile navigation simpler as you can't use ESC to close `photoswipe` as on desktop 
tested locally

back button press to open and close photoswipe

---

package.json
src/pages/shared-albums/index.tsx
src/utils/collection/index.ts
yarn.lock

Tested by generating ck with both hex and bs58 encoding and verified that the shared album is rendering fine for both cases.

Shared-url: switch to bs58 encoding for ck

---

package.json
yarn.lock

`photoswipe` version was updated `4.1.4` on master update in PR #369 
but was mistakenly reverted back in PR #370
updating Photoswipe version in the release

update photoswipe release

---

src/components/pages/gallery/PlanSelector.tsx
src/utils/billing/index.ts
src/utils/strings/englishConstants.tsx

- show contact support screen if the user has an active Paypal subscription and he tries to update his plan
tested locally by adding a Paypal subscription and simulating

paypal support

---

.eslintrc.json
package.json

Fixed `package.json` prebuild command as it didn't work on Windows. And added root variable in `.eslintrc.json` as in desktop app it had ambiguity due to two packages of ESLint.

Fixed config for desktop app

---

src/services/upload/exifService.ts
src/utils/error/index.ts

exifr function has an option to convert EXIF Format date to date instance, but it's failing sometime and it returns the date without converting which causes the date.getTime() call to fail
added checks to log the date format which are failing and gracefully handle the failure
- handle cases when `exifr` date revive fails
tested locally

parseExif by self if exifr return unparsed value

---

src/components/CollectionShare.tsx

- key returned from by deriveInteractiveKey function is already B64 , was mistakenly reencoded
- fix minor styling  link expiry option `never`  was not shown in the center
- tested the password is working
- verified style change

Fix manage sharable url

---

src/components/FileList.tsx
src/components/pages/gallery/UploadProgress.tsx

fixing -> the progress percentage getting ellipsed for in-progress items 😬 
tested locally

fix ellipsing for in progress items

---

src/utils/file/index.ts

`x in [a,b,c]` way of checking for some reason worked for array [0,1], but in general, it doesn't work 
for example 5 in [0,5] returns false 
so changing to the correct way 
tested it locally and on console

fix isImageOrVideo check

---

src/components/pages/gallery/Upload.tsx

^title
tested on fresh account
- uploading mutiple folder -> choice modal shown correctly
-  uploading a single folder -> creates a new album with folder name and uploads
- uploading single file -> creates album with name "My First Album" and uploads to it

show choice modal on first upload if multiple folders detected

---

src/pages/gallery/index.tsx
src/services/upload/metadataService.ts
src/utils/time/index.ts

^ title
tested for these sample 
```
_screenshots_ 
Screenshot_20181227-152914.jpg =>  
Date Thu Dec 27 2018 15:29:14 GMT+0530 (India Standard Time)
_Whatsapp images and videos_
IMG-20190330-WA0002(1).jpg  =>  
Date Sat Mar 30 2019 00:00:00 GMT+0530 (India Standard Time)
IMG-20171218-WA0028.jpg  =>  
Date Mon Dec 18 2017 00:00:00 GMT+0530 (India Standard Time)
VID-20171218-WA0028.mp4  =>  
Date Mon Dec 18 2017 00:00:00 GMT+0530 (India Standard Time)
_google motion photos_ 
IMG_20130816_145041-MOTION(1).gif  =>  
Date Fri Aug 16 2013 14:50:41 GMT+0530 (India Standard Time)
VID-WA0028.mp4  =>  
Invalid Date
2014-08-25_17.15.33.jpg  =>  
Date Mon Aug 25 2014 17:15:33 GMT+0530 (India Standard Time)
IMG-20161224-WA0014.jpg  =>  
Date Sat Dec 24 2016 00:00:00 GMT+0530 (India Standard Time) …
```

add logic to extract date from filename

---

src/services/upload/metadataService.ts

so when a property object is assigned to another object, it creates a shallow copy and hence when I edited the 
`extractedMetadata.creationTime` , it also edited the creation time on the `NULL_EXTRACTED_METADATA` too which was used to initialise it
fixed it by not editing the value, instead of adding a fallback to the initialisation of creationTime in the response object 
tested locally by trying to upload multiple files with no EXIF data but having DateTime in the filename so that the issue would get triggered but it didn't occur. All is good

prevent  metadata value from getting cached

---

src/components/PhotoFrame.tsx
src/components/pages/gallery/PreviewCard.tsx
src/utils/error/index.ts

It randomly occurred in the dev environment, unable to reproduce it consistently, but this should help avoid it from happening in any case
checking that the  `file` is not undefined or null before proceeding into the function will prevent any error caused by trying to access a property on an `undefined` variable 
theoretically it should work

fix can't read property of undefined (reading metadata) error  

---

src/components/pages/gallery/PlanSelector.tsx

we were only showing the manage family option for stripe, changed it to show it for all type of paid subscription 
simulated the behaviour with  free and AppStore paid subscription, both have desired options

show family portal for all type of paid susbcription

---

src/components/Sidebar.tsx
src/utils/billing/index.ts

show subscription in family plan view only if the user has at least one active/invited member in his family
tested with 1 invited member and a family with no invited or active member other than the admin

update family plan view 

---

.gitmodules

I don't have SSH access to GitHub configured on my machine, and instead use/prefer the PAT (Personal Access Token) based access. In any case, the submodule is a public repository, so the credentials shouldn't matter. However, if we use the git:// URL for the submodule, then git fails to fetch it if SSH isn't configured even if it is public.
So use the less restrictive HTTPS based URL. This will work for everyone, even if they haven't configured any private GitHub credentials.

Modify submodule URL to use HTTPS

---

src/services/upload/uploadManager.ts
src/utils/storage/localStorage.ts

handle post upload task error gracefully  
- tested that breaking errors like subscription expired and session expired are propagated 
- but other errors are caught and logged and don't break other uploads

better handle upload error 

---

src/services/readerService.ts

add file size to log to help with 
debugging https://sentry.ente.io/organizations/ente/issues/2051/?project=2&query=is%3Aunresolved&statsPeriod=14d
`Error: file reading has failed, file size= 3.86 GB , reason= NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
at FileReader.reader.onerror (readerService.ts?1565:18:17) {msg: 'ffmpeg metadata extraction failed', info: undefined}
`
checked locally filesize is getting logged correctly

add file size to failed to read file error log

---

src/components/pages/gallery/PreviewCard.tsx

updateURL is a optional parameter, so adding a exists  check before running it
fixes https://sentry.ente.io/organizations/ente/issues/2560/?project=2&query=is%3Aunresolved+preview+card&statsPeriod=14d 
tested locally

fix previewcard issue

---

src/components/PhotoFrame.tsx

When any image / video / live photo item is clicked and is closed while it has not yet completed loading, it throws an error on the `updateSize` call due to the `_listeners` property being null as it had been destroyed on close.
This fix checks if photoswipe is open before calling `updateSize`.
- Tested locally.

Fix photoswipe null error

---

src/components/icons/LeftArrow.tsx
src/components/pages/gallery/SelectedFileOptions/DeduplicateOptions.tsx
src/pages/deduplicate/index.tsx

show clear selection button if count is not equal to zero , else give the back button
tested locally

add clear selection button on dedupe page

---

src/utils/error/index.ts
src/utils/sentry/index.ts

`sentry util `was importing `error util` which was importing `strings constants` which has a reference to window, which caused the error
fixed by copying the  `errorWithContext` function  directly in `sentry util` hence removing the  
`error util` dependency from `sentry util` 
tested locally video upload is working

fix window is undefined in ffmpeg worker error

---

src/components/Sidebar.tsx

use anchor tag as the base component for support link so that email-id can seen by hovering over it

better support link

---

src/pages/gallery/index.tsx
src/utils/sentry/index.ts

add `syncWithRemote` failed logs
and add the complete error object in context to get custom Error properties  hidden by sentry

more  logs

---

src/pages/two-factor/verify/index.tsx

https://sentry.ente.io/organizations/ente/issues/3379/
move user null check before accessing the twoFactorSessionID property to avoid the null read error
tested locally by navigating to two-factor/verify -> user is correctly redirected to root if user twoFactorSessionID is missing

fixes Cannot read properties of null (reading 'isTwoFactorEnabled') 

---

src/services/upload/uploadManager.ts

files whose metadata extraction failed didn't get a map entry and caused a `can't read property of undefined` error when was they were accessed
putting null values, for such cases to avoid the error

better handle metadata extraction error 

---

src/services/upload/hashService.tsx
src/services/upload/metadataService.ts
src/services/upload/uploadManager.ts
src/services/upload/videoMetadataService.ts
src/utils/crypto/index.ts
src/utils/crypto/libsodium.ts
src/worker/crypto.worker.js

hashing was not offloaded to the worker.
fixes that 
this should ideally, increase performance, but testing showed this increases time 🥲 , still doing it 
tested locally, hash generation working and it matches the earlier generated hash for same file

offload hashing to worker

---

src/services/upload/uploadManager.ts

this is to fix the Neeraj bhaiya issue of upload crashing with a generic upload message
so, we don't let the single file error bubble up, we just log and add it to the progress bar view
tested locally

fix complete upload crash- on localstrorage write fail

---

src/services/downloadManager.ts
src/utils/file/index.ts

use typed blob to create object URL, so that safari understands the file and plays it 
tested locally

fix video not playable on safari issue

---

src/pages/gallery/index.tsx
src/services/collectionService.ts
src/utils/collection/index.ts

`fromCollection` was mistakenly set as `toCollection` itself
tested locally

fix move to collection

---

src/components/Login.tsx
src/components/SetPasswordForm.tsx
src/components/SignUp.tsx
src/components/SingleInputForm.tsx
src/pages/change-password/index.tsx
src/pages/credentials/index.tsx
src/pages/generate/index.tsx
src/pages/verify/index.tsx

- added [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute, this solved the autofill problem on firefox and safari, but not on chrome
- for chrome had to add a hidden input.
adding hidden input has a problem
let's say a user selects an autofill suggestion and then updates the email manually then the password field is not changed and hence on submitting the form, the password manager sees that the email is something that it doesn't recognise and there is a password (that was auto-filled but hidden from the user) and hence suggest to save this as a new login.
tested on chrome and firefox and safari

Fix password autofill

---

src/services/typeDetectionService.ts
src/utils/file/index.ts

https://sentry.ente.io/organizations/ente/issues/2679/?project=2&referrer=slack
fileFomat return could be null which was not handled before trying to convert the format to lowerCase

fix file metadata extraction failed 

---

src/pages/gallery/index.tsx
src/services/collectionService.ts

https://sentry.ente.io/organizations/ente/issues/2733/?project=2&query=is%3Aunresolved
added check to prevent `null` users. 
tested locally

fix getCollectionSummary failed 

---

src/components/PhotoSwipe/InfoDialog/index.tsx
src/services/upload/exifService.ts

so for some reason, some files don't have location metadata but the EXIF data has the location value, maybe the file was uploaded when we had an EXIF parsing bug.
For now, have added a fallback to the EXIF location if that's available 
TODO FOR FUTURE:  backfill the location from EXIF if it's missing in enteFile metadata
fixes #661
tested locally

show exif location as fallback if metadata is missing location 

---

src/services/downloadManager.ts
src/services/publicCollectionDownloadManager.ts

we added a check based on the file extension to check if the file is heic so that we can store the file without the  `converted` in the cache if it doesn't need conversion and will be the original file and hence redownload won't need us to download the original file again.
This broke for the current case where the file extension was jpg, which resulted in us not converting the file. but the file was actually heic.
Also, there are more cases we need to handle if we want to avoid redownloading files (like if we have the original file, and want the converted file then we can avoid downloading the file as that file can be converted) but the benefits don't seem that attractive compared to the code complexity it will cause. 
so removing that logic. Now if we get a file for preview, we save it …

don't use file extension to check if file need conversion

---

src/services/downloadManager.ts
src/services/publicCollectionDownloadManager.ts
src/services/upload/thumbnailService.ts
src/utils/file/index.ts

refactored convertForPreview to be used only for generating preview URLs of file 
and separate out the conversion of live photo and heic image into separate functions.
tested locally for both normal gallery and public-URL gallery and tested live photo preview

refactor conversion for preview

---

src/services/ffmpeg/ffmpegService.ts

HEVC thumbnail generation is taking longer than 10sec (the earlier timeout ) 
Have increased the timeout to 30 sec
tested locally

increase timeout for FFmeg thumbnail generation

---

src/services/publicCollectionDownloadManager.ts

attach the missing `passwordToken`header for video download
tested locally

fix downloadFile for video download

---

src/constants/billing/index.ts
src/services/billingService.ts

need to proxy the desktop redirect URL through the `payments gateway`  as the `ente://app` is not a valid redirect URL for stripe 
tested locally by trying to buy a new subscription and then clicking on back which sends the user to `redirectURL` we have sent with the request

fix buy subscription on desktop

---

src/components/pages/gallery/PlanSelector/card/index.tsx
src/utils/billing/index.ts
src/utils/strings/englishConstants.tsx

update handling of non-stripe subscription 
we show the following dialog for all paid bitpay/paypal subscription
and for mobile subscriptions  this screen
tested screen for  all payment types

mail to manage paypal and bitpay subscription

---

public/.well-known/apple-app-site-association

The team ID changes when we build the app from the new account. Add the new one to the Apple site association.
Currently untested. Once this is deployed, we can test with the new development/TestFlight build of frame to ensure that the shows the saved credentials for web.ente.io.

Add the bundle ID of the US mobile app to apple site association

---

sentry.properties
sentryConfigUtil.js
src/constants/sentry/index.ts
src/utils/collection/index.ts
src/utils/logging/index.ts
src/utils/sentry/index.ts

- move non-private sentry config to sentry.properties
- make the default environment to `production`, so logging error to sentry is the default behaviour if no flags are set
- and logging to console is special behaviour which happens when an environment is explicitly set to  `development`
tested on preview deployment error logging is working

Store sentry config in code

---

src/constants/billing/index.ts
src/services/billingService.ts

use `desktop-redirect` as a proxy redirect URL for the customer portal too 
tested locally

fix redirect url for customer portal sent for electron app

---

src/components/Sidebar/SubscriptionStatus/index.tsx
src/components/Upload/Uploader.tsx
src/utils/billing/index.ts

hasStripeSubscription had an active subscription check and so it return false when checked for an expired stripe subscription hence the renew button check for stripe subscription returned false and so the checkout session was called instead of opening customer portal 
Also passing around `billingService.redirectToCustomerPortal` without binding `this` to it was causing problem
tested locally, all calls to `billingService.redirectToCustomerPortal` are now working and expired subscription opens customer portal

fix expired subscription renewal 

---

src/components/PhotoFrame.tsx
src/components/PhotoList.tsx
src/components/PhotoSwipe/index.tsx
src/pages/_app.tsx
src/pages/gallery/index.tsx
src/pages/shared-albums/index.tsx
src/utils/strings/englishConstants.tsx
src/utils/ui/index.tsx

added option to delete the current from the `photoswipe` view 
https://user-images.githubusercontent.com/46242073/194831223-4dddaa8f-1a7a-4701-a39f-612570c51188.mov
- tested that trash files work
- file is moved to the trashed section 
- refreshed to confirm the server API call is happening

Photoswipe delete file option

---

src/components/PhotoFrame.tsx

caught the uncaught error if getFileIndexFromID fails, which was leading to an "unexpected error" page being shown
happened when a file was deleted after its download was initiated and hence when the download was completed we had no files matching the fileID (and trash has not synced till then ) 
tested locally

handle uncaught exception

---

src/services/heicConverter/heicConverterService.ts
src/services/upload/uploadManager.ts
src/services/watchFolder/watchFolderEventHandlers.ts
src/services/watchFolder/watchFolderService.ts

- avoid logging very large objects 
-  remove error local logs which don't add any new context as logError is already logged 
tested locally, the app no longer hangs during the watch folder activities

Fix logging causing app to hang

---

src/pages/_app.tsx

https://sentry.ente.io/organizations/ente/issues/4069/?project=2&referrer=slack
`InvalidStateError: Failed to get ServiceWorkerRegistration objects: The document is in an invalid state.`
This error was thrown when service registration was tried to be accessed on an electron 
added a `!isElectron()` check to avoid that
Service worker are anyways disabled this is just a cleanup code which as written to remove any added serviceWorker from browsers
tested locally

don't search for service worker on electron

---

src/utils/logging/index.ts
src/utils/sentry/index.ts

`logError` call for `addLogLine` failure caused an infinite loop as `addLogLine` was again called inside `logError`
added option to pass avoid addLogLine flag to prevent  
tested locally by manually failing the addLogLine function

Fix too much recursion error

---

src/components/PhotoSwipe/index.tsx

fixes minor issues with `photoswipe` delete option
- handle deleting the last image in the list, loop to the front of the list
- handle case where all files are deleted
- don't show delete option in shared collection and trash section(will improve later on)
tested locally

fix photoswipe delete option issues 

---

src/components/PhotoList.tsx
src/components/Upload/Uploader.tsx
src/components/pages/gallery/PlanSelector/card/index.tsx
src/pages/deduplicate/index.tsx
src/pages/gallery/index.tsx
src/services/deduplicationService.ts
src/services/fileService.ts
src/services/publicCollectionService.ts
src/services/upload/uploadHttpClient.ts
src/services/upload/uploadManager.ts

arr1.push(...arr2) was essentially converted to arr1.push(arr21,arr22,....arr2n) and this caused stack overflow issue because maximum parameter count 
> But beware: by using apply this way, you run the risk of exceeding the JavaScript engine's argument length limit. The consequences of applying a function with too many arguments (that is, more than tens of thousands of arguments) varies across engines. (The JavaScriptCore engine has hard-coded [argument limit of 65536](https://bugs.webkit.org/show_bug.cgi?id=80797).)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#using_apply_and_built-in_functions
testing  locally with 112000 files upload

fix stack overflow on push 

---

src/components/Notification.tsx
src/components/Sidebar/HelpSection.tsx
src/components/Upload/UploadProgress/dialog.tsx
src/components/Upload/Uploader.tsx
src/components/pages/gallery/LinkButton.tsx
src/pages/_app.tsx
src/pages/gallery/index.tsx
src/services/electron/update.ts
src/themes/darkThemeOptions.tsx
src/types/Notification/index.tsx
src/types/electron/index.ts
src/types/gallery/index.ts
src/utils/common/index.ts
src/utils/strings/englishConstants.tsx
src/utils/ui/index.tsx

Show notification to manually download updates if the app doesn't support auto update to that version.
see updater changes  https://github.com/ente-io/bhari-frame/pull/91

Manual update download

---

next.config.js
src/components/Sidebar/DebugLogs.tsx
src/pages/_app.tsx
src/services/electron/common.ts
src/types/electron/index.ts
src/utils/logging/index.ts
src/utils/sentry/index.ts
src/utils/user/index.ts

- use electron-side generated sentry ID on desktop
- log sentry ID at the start instead of time of log export 
tested locally

Fix sentry id logging on desktop

---

src/utils/time/index.ts

updated getUnixTimeInMicroSeconds function to reject date string "0000:00:00 00:00:00".
tested locally

improve invalid date string handling 

---

src/components/Search/SearchBar/searchInput/index.tsx
src/pages/_app.tsx

some use-effects, broke while fixing the #782  😬  
fixes them 
The format for use effect is 
`useEffect(()=>{},[state])`
I by mistake moved the `[state]` inside the `{ }` while refactoring them 

fix use effects

---

src/utils/time/format.ts

string constants import indirectly led to importing window in a worker, which caused a runtime error 
patched it by removing constant import
tested locally

remove constants fom time format

---

src/components/PhotoViewer/index.tsx

reenabled copy shortcut for browser with Clipboard Item API support 
tested locally

reenable copy shortcut for browser having Clipboard Item API

---

src/components/PhotoViewer/index.tsx

forgot to add  close button  shortcut info
before 
after

fix close button hover info  

---

.eslintrc.json

> Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
our images are either  decorative , or user uploaded , so doesn't make sense to add alt text
check locally

disable jsx-a11y/alt-text eslint rule

---

src/services/upload/fileService.ts
src/services/upload/hashService.tsx
src/services/upload/metadataService.ts
src/services/upload/uploadManager.ts
src/services/upload/uploadService.ts

add chunk count check during file hashing to prevent possible infinite loop
also, use a separate upload worker for hashing 
trying to fix user issue - https://github.com/ente-io/bhari-frame/issues/117
tested generated hash for a file  matches the earlier generated file hash
tested with the sample dataset

prevent possible infinite loop during file hash generation 

---

src/components/Collections/CollectionSelector/index.tsx
src/components/Upload/Uploader.tsx
src/services/watchFolder/watchFolderService.ts

fix cancelling on the choice screen or collection selector screen and then trying a new upload didn't work.
The `uploadRunning` state was not reset after the the close of dialogs , and hence that blocked further uploads
a better solution will be to move to having a option to await on dialog response, which i will do in sometime in future 
for now this should fix the issue  
tested locally

Fix upload cancel on collection-selector screen lead to bad state , and no new uploads were accepted

---

src/constants/upload/index.ts

add mp4 to the list of formats missed by the file-type detection library

add mp4 format missed by type detection library

---

src/components/Upload/Uploader.tsx
src/services/upload/fileService.ts
src/services/upload/magicMetadataService.ts
src/services/upload/uploadManager.ts
src/services/upload/uploadService.ts
src/services/upload/uploader.ts
src/types/file/index.ts
src/types/magicMetadata/index.ts
src/types/upload/index.ts

^ title 
- also fixed the retry upload  in the public upload

move uploaderName to pubMagicMetadata

---

src/services/upload/livePhotoService.ts
src/utils/strings/englishConstants.tsx

- use image extension as live photo extension
- and remove mention of ELP in live photos are being merged help text in the upload dialog
tested locally

remove the use of elp extension

---

src/components/PhotoViewer/index.tsx

^ title 
tested existing shortcuts work and info is not closed on "i" button press

disable info dialog close with i button

---

src/components/SignUp.tsx
src/components/SubmitButton.tsx

OTP was sent even when the user entered mismatched password and confirm-password.
Fixes it by confirming that password before sending OTP
Also, fixes the submit button not being disabled when terms are not accepted    
tested locally

Otp on mismatch password 

---

src/components/PhotoFrame.tsx

The second file Search was causing app to crash.
Fixes it by only updating the files list when data/ location search is done.
@Jishnuraj9  confirmed his issue is fixed

fix unhandled expection on file search

---

src/services/upload/thumbnailService.ts

getting sentry log for thumbnail just greater than 100KB( like 100.58 KB)
updated the report large thumbnails only on condition that they are greater than 150KB

don't report thumbnail upto size of 150KB

---

src/services/collectionService.ts
src/services/fileService.ts
src/services/migrateThumbnailService.ts
src/services/upload/encryptionService.ts
src/services/upload/fileService.ts
src/services/upload/uploadService.ts
src/types/file/index.ts
src/types/upload/index.ts

updated `EncryptionResult` to a generic interface allowing three types `Uint8Array` , `DataStream`, `string`
- `Uint8Array` -> is used for thumbnail and small-sized files (< 20MB)
- `DataStream` ->is used for large files (>20MB)
- `string` -> is used for metadata 
the changes are just for types, so the typescript/next compiler would have thrown any issue

Refactor upload types

---

src/components/FixCreationTime/index.tsx
src/components/FixCreationTime/options.tsx

Fix alignment of entries within the fix-time dialog

---

src/utils/time/index.ts

^ title 
FFmpeg is returning zero as creation time for some files (when it is unable to find `creationTime` )
rejecting Unix time zero to prevent the setting `creationTime` as zero 
tested locally

ignore zero unix time

---

configUtil.js
public/_headers

Tested by: making this change, and connecting to Phoenix museum (which serves the secondary hot storage), and verifying that the CSP policy reports that were getting logged to console no longer appear.

Add the URL of the secondary hot storage in the CSP whitelist

---

src/services/collectionService.ts
src/types/magicMetadata/index.ts
src/utils/collection/index.ts

Description:
This change convert a quick link album to a regular album on rename. 
Test Plan
- Verified that renaming quick link is converting it to an album
- Verified that rename for archived quick link is working as expected.
- Verified that rename for regular album is working as expected

Handle rename for quick link albums

---

src/services/wasm/ffmpeg.ts
src/utils/temp/index.ts

^ title
fixes by using only the extension part to generate a temp file inside wasm FFmpeg
tested locally with a file for which it was detected by jishnu

fix ffmpeg thumnail generation for non english named files

---

src/components/Collections/CollectionSelector/index.tsx
src/components/Upload/Uploader.tsx
src/pages/gallery/index.tsx

backdrop click to close the collectionSelectorDialog was not triggering `onCancel` event and hence the `uploadManager` uploadProgress state was not reset and, new upload got blocked because of that
Fix the issue by calling userTriggeredClose callback for both types of close event 
tested locally

Handle backdrop click event  to  canceling running upload

---

src/components/Collections/CollectionOptions/SharedCollectionOption.tsx

git push --set-upstream origin change-leave-shared-album-option-icon

Change leave shared album option icon

---

next.config.js
package.json
yarn.lock

fix warning
> next-transpile-modules@10.0.0: All features of next-transpile-modules are now natively built-in Next.js 13.1. Please use Next's transpilePackages option :)
tested build and ran locally

remove next-transpile-modules package

---

package.json
yarn.lock

transpilePackages is only present in v13.1 we were on v13.0
> Invalid next.config.js options detected: 
The root value has an unexpected property, transpilePackages, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
the warning …

upgrade next to latest

---

src/components/Collections/CollectionListBar/CollectionCard.tsx
src/components/Collections/styledComponents.ts
src/constants/collection/index.ts
src/services/collectionService.ts
src/themes/darkThemeOptions.tsx
src/themes/lightThemeOptions.tsx
src/utils/collection/index.ts

1. Changed archived Album icon color to fixed.strokeMutedWhite
2. moved album icon to left bottom
3. show share (people icon) for self shared albums
4. show link icon for albums with just public link
Share Icon is for only those albums not been shared by anyone via email. Once you share any link shared albums via email, the link icon will disappear and people icon would be shown instead.

Album icon change

---

src/utils/file/index.ts

create typed object URL for safari else it doesn't understand that the file is video
tested locally

fix video playback on safari

---

src/components/PhotoList.tsx

fixed the date positioning, so that it occupies the space after the gap grid item 
before 
after
tested locally

fix gap div between dates missing

---

src/components/Collections/CollectionOptions/FavoritiesCollectionOption.tsx
src/components/Collections/CollectionOptions/QuickOptions.tsx
src/components/Collections/CollectionOptions/index.tsx
src/components/OverflowMenu/menu.tsx
src/services/collectionService.ts
src/themes/darkThemeOptions.tsx
src/utils/collection/index.ts

Album header change

---

src/components/PhotoViewer/index.tsx
src/constants/upload/index.ts
src/services/typeDetectionService.ts
src/services/upload/exifService.ts

- better-named errors 
- avoid logging known format that doesn't have EXIF
- better logs for unsupported formats by the `exifr` llibrary
tested locally by triggering the getRawExif function for 
- jpeg, 
- webp 
- gif files
- ran the upload dataset exif parsing test

improve exif error logging

---

src/pages/gallery/index.tsx

deletedFileIDs was used to hide the deleted files from UI, preemptively so that the files were quickly gone.
But,  Not clearing the deletedFileIDs after completion of the action, caused the file to be not visible on the UI even after the file was restored 
tested locally

 file not shown on ui after restore

---

src/services/collectionService.ts
src/services/trashService.ts

- fixed `getCollection` shallowing the error and not rethrowing causing undefined collection to be saved to local DB
- migrated local DB to remove saved undefined deleted-collection entries
tested locally by reproducing the issue and confirming the fix and the migration works

Fix trash sync fail

---

src/constants/collection/index.ts

- UPLOAD_NOT_ALLOWED_COLLECTION_TYPES list had outgoing shared item in the list
tested locally

fix upload to outgoing shared album

---

src/components/PhotoFrame.tsx

fix `useEffect` cleanup logic,  call removeEventListener instead of addEventListener 
tested locally

fix shift key event listener cleanup 

---

src/utils/strings/englishConstants.tsx

- removed the extra single quote (`'`)

Fix copy for disable link sharing

---

src/components/PhotoFrame.tsx
src/components/pages/gallery/PreviewCard.tsx
src/components/pages/gallery/SelectedFileOptions.tsx
src/pages/gallery/index.tsx

- re-enabled incoming album file selection
- file selection option has just download
also added the missing download option on selection to uncategorized album
tested locally

Allow incoming album selection

---

src/components/MemberSubscriptionManage.tsx
src/components/Sidebar/SubscriptionCard/contentOverlay/family/index.tsx
src/components/Sidebar/SubscriptionCard/contentOverlay/index.tsx
src/components/Sidebar/SubscriptionStatus/index.tsx
src/components/Sidebar/userDetailsSection.tsx
src/components/pages/gallery/PlanSelector/card/index.tsx
src/services/userService.ts
src/utils/billing/index.ts
src/utils/user/family.ts

- refactored family utils, into a separate file 
This prevents `window` object from being referenced in a worker. 
The cause of the issue is Mui component using window object, which is import of the  in the `englishConstant` file. And indirectly leads to the window object being referenced in the worker. 
This is just a temporary fix, a better solution would be to separate the englishConstants file into `englishConstants` and `englishComponents`.
But that requires a lot of refactoring so did this for now.
Only imports have changes, so just tested the build is working properly

refactor family utils

---

src/services/exportService.ts
src/services/motionPhotoService.ts
src/utils/file/index.ts

- move the original name from file title logic to inside of decodeMotionPhoto
- wrapped `downloadFile` util in try-catch block
- moved image exif data updating logic to else block
- tested playback of a live photo 
- tested download of image, video and live photo

Motion photo service ML updates

---

src/services/searchService.ts

Can build and run locally. Also tested search. Didn't specifically test this code path but that should be fine because this function currently isn't even called because its caller (`getLocationSuggestions`) is unused,

Remove deprecated search API

---

package.json
src/types/machineLearning/index.ts
src/utils/machineLearning/clustering.ts
yarn.lock

removed unused react-d3 tree package
fixes 
- https://github.com/ente-io/photos-web/security/dependabot/28
- check build 
- the code was not being called from anywhere, the only usage was in the `ml-debug` page which was removed already, the component commented code was kept around just in case it might be needed in future

fix security warning 28

---

src/components/ExportModal.tsx
src/components/Sidebar/HelpSection.tsx
src/components/Sidebar/index.tsx
src/services/exportService.ts
src/utils/export/index.ts

- added `keepMounted` prop to sidebar, to avoid dismounting exportModal
- fix enteSpinner for export in progress size
- fix possible StackOverflow issue, caused by spreading parameter in `new Array(...fileSet);` 
- fixed exportInProgress not reset on error

Fix export issue

---

src/pages/gallery/index.tsx
src/services/trashService.ts

fix trash sync, by using the non-merged file list to set the new state after trash fetch
tested by deleting a file and seeing it synced in the trash and then emptying trash and confirming its gone

fix empty trash not working 

---

src/services/downloadManager.ts
src/services/publicCollectionDownloadManager.ts
src/services/upload/encryptionService.ts
src/services/upload/fileService.ts
src/services/upload/hashService.tsx
src/services/upload/livePhotoService.ts
src/services/upload/metadataService.ts
src/services/upload/uploadService.ts
src/utils/crypto/index.ts
src/utils/crypto/libsodium.ts
src/worker/crypto.worker.ts

- added missing worker types to function parameters
-  renamed `initDecryption` function to `initChunkDecryption`, the convention used for other similar functions (`initChunkEncryption` and `initChunkHashing`)
- similarly renamed `decryptChunk` to `decryptFileChunk` following the convention used for `encryptFileChunk` and `hashFileChunk`
- made `key` compulsory parameter in `encryptChaChaOneShot` function ,as it always requires the key (used for encryption metadata and thumbnail with fileKey)
- removed `key` parameter from `encryptChaCha` function as it always generates its own key  (used for encrypting file data)
- made  `key` compulsory in `encrypt`, `encryptUTF8`, `encryptToB64` function and make a new function `generateKeyAndEncryptToB64` for case where new keys needs to be generated …

Refactor CryptoWorker

---

package.json
src/components/PasswordStrength.tsx
src/components/SetPasswordForm.tsx
src/components/SignUp.tsx
src/constants/crypto/index.ts
src/themes/darkThemeOptions.tsx
src/utils/crypto/index.ts
src/utils/strings/englishConstants.tsx
yarn.lock

- add password strength check validation to signup and password change flow 
- added UI to show that the current entered password strength
- weak passwords are not allowed 
the score scale from the package readme 
```
result.score      # Integer from 0-4 (useful for implementing a strength bar)
0 # too guessable: risky password. (guesses < 10^3)
1 # very guessable: protection from throttled online attacks. (guesses < 10^6)
2 # somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8)
3 # safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10)
4 # very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)
```
Have used 
```
1. Weak = 0-2
2. Moderate = 3
3. Strong = 4
```
signup page 
change password page …

Add password strength check

---

src/utils/crypto/libsodium.ts

- add missing `sodium.ready` check  
found and tested with desktop app where this was the first crypto function to run hence throwing the sodium not ready error

Refactor CryptoWorker 

---

src/services/exportService.ts
src/utils/sentry/index.ts

- await missing on `addFilesQueuedRecord`, which might be the reason for the user error 
```
error: TypeError Cannot read properties of undefined (reading 'filter') TypeError: Cannot read properties of undefined (reading 'filter')
at Object.addFileExportedRecord (ente://app/_next/static/chunks/5105-111b35ea73525f6c.js:1:117081)
at async Object.fileExporter (ente://app/_next/static/chunks/5105-111b35ea73525f6c.js:1:116259)
at async Object.exportFiles (ente://app/_next/static/chunks/5105-111b35ea73525f6c.js:1:115237)
```
which was pointing to this line
>exportRecord.queuedFiles = exportRecord.queuedFiles.filter(
https://github.com/ente-io/bada-frame/blob/b3ec5423a64ad831f37bd3e5f107506239898be0/src/services/exportService.ts#L294
> await this.addFilesQueuedRecord(exportDir, files); …

fix missing await issue

---

src/components/ExportModal.tsx
src/services/exportService.ts
src/utils/error/index.ts

- enabled the promise eslint rule temporarily, to check and fix it for export flow only  
- added missing try catch wrappers around code in useEffect block, which could cause uncaught expectations 
- https://github.com/ente-io/photos-web/pull/967/files#diff-ce20bcf03cbfdc73a257b87d177ed96355d0cb822ab638e246f65ab285caaa1bR73-R86
- https://github.com/ente-io/photos-web/pull/967/files#diff-ce20bcf03cbfdc73a257b87d177ed96355d0cb822ab638e246f65ab285caaa1bR94-R109
- `void` main() -> void is added for when we intentionally want to not await a function. 
This is done because useEffect function can't be async and hence we can't use inside `await` it
https://github.com/ente-io/photos-web/pull/967/files#diff-ce20bcf03cbfdc73a257b87d177ed96355d0cb822ab638e246f65ab285caaa1bR112
- added awaited to …

Fix all promise related eslint issue for export

---

sentry.properties
src/constants/sentry/index.ts

- updated DSN and project name (for both prod and debug )
- updated cf with a new token to upload source maps 
- for prod, the values are changed in the `sentry.properties` file
- for debug mode, the values are overridden using environment variable in the cf pages setting 
tested with debug build that the error is showing up as expected, with `stacktrace`

update sentry dsn

---

src/components/Sidebar/index.tsx

The sidebar is stuck in the position, where the user closed it last time.  
It was caused by making the sidebar permanently mounted which was to fix export progress not working after the sidebar close and open issue 
added logic to reset the scroll position when the user closes the sidebar 
tested the fix locally

reset sidebar scroll on close

---

next.config.js
package.json
src/components/Collections/styledComponents.ts
src/components/EnteDrawer.tsx
src/components/MachineLearning/ImageViews.tsx
src/components/MachineLearning/MlDebug-disabled.tsx
src/components/MachineLearning/PeopleList.tsx
src/components/Navbar/base.tsx
src/components/PhotoList.tsx
src/components/Search/SearchBar/styledComponents.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/styles/SpecialPadding.ts
src/themes/createEmotionCache.ts
tsconfig.json
yarn.lock

Facing issues, with `styled-component`, not properly rendering styles and styles randomly breaking at various instances.
Found an open issue on mui (https://github.com/mui/material-ui/issues/29742), related similar issue.
migrated to use emotion. 
opening /gallery directly on https://share-screen.bada-frame.pages.dev/gallery was causing rendering issues with the collection sort option
doing the same on https://migrate-to-emotion.bada-frame.pages.dev/gallery, is working without issues

Migrate to emotion

---

public/locales/en/translation.json
src/components/ExportInProgress.tsx
src/components/ExportModal.tsx
src/services/exportService.ts
src/types/export/index.ts
src/utils/export/index.ts

- fix new updates getting missed when export is already in progress
- better handle no folder selected state.
- removed failed files state  from export record JSON too 
- fixed progress bar increasing for failed files too
added "export starting state" loading message 
- tested by uploading new files when export is in progress and verified that they are queued for export after the current export finishes
- tested starting export / running continuous export with no export folder selected.
- tested normal export
- tested progress bar fix by explicitly failing files

Fix continous export bug

---

public/locales/en/translation.json

Fixes a typo for the "photos_count_zero" english translation. It used to be "No memory", but it has been corrected to "No memories".
Check `/gallery` without any memories in your account and open the sidebar. The text in the bottom right of the storage indicator should be "No memories".

fix: typo for "No memory"

---

public/locales/en/translation.json
src/components/PhotoFrame.tsx
src/constants/upload/index.ts
src/pages/_app.tsx
src/pages/auth/index.tsx
src/pages/gallery/index.tsx
src/services/authenticator/authenticatorService.ts
src/utils/common/index.ts
src/utils/error/index.ts
src/utils/error/ui.ts
src/utils/storage/mlIDbStorage.ts

- fix syncWithRemote logging handled errors
- add txt and HTML to known non-media file formats to ignore logging their upload fail error
- ignore msrc already set warning in case new url is same as old and ignore it as it is possible that component render can call the function multiple time, but its harmless and can be ignored.
- added checks to prevent ml DB initialization on the browser  
- handle auth key not set on server and remove logging for the case 
tested locally

Update error handlings

---

src/constants/upload/index.ts
src/services/typeDetectionService.ts
src/services/upload/uploader.ts

sentry reported some gif failing type detection. 
https://sentry.ente.io/organizations/ente/issues/1195/?project=2&referrer=webhooks_plugin
Added gif to missed file format list to be uploaded even on type detection failure
Also, added fileSize info to the error logs, for extra debugging info if this happens again 
- tested change by intentionally breaking gif type detection and verifying that was uploaded properly
- ran sample dataset upload

update file type detection error handling 

---

package.json
src/components/Chip.tsx
yarn.lock

- missed removing styled-component dependency while migrating to `emotion`
Seems like internally MUI was still relying on some `styled-components` because of the yarn package resolution we used earlier. 
Fixed it by removing and adding back the mui/material package 
The app is building successfully and did basic sanity testing withing the app

Remove styled component dependency

---

next.config.js
tsconfig.json

The check icon was not shown on the hover on Preview Card. 
Caused by MUI emotion migration, Nested component references were not properly handled by MUI styled util
Fixed it by using the  `importMap` config provided by the MUI team to fix it https://github.com/mui/material-ui/issues/27380#issuecomment-928973157
tested locally, the issue is fixed

fix emotion migration issue

---

src/services/ffmpeg/ffmpegService.ts
src/services/upload/thumbnailService.ts
src/utils/comlink/ComlinkCryptoWorker.ts
src/utils/comlink/ComlinkFFmpegWorker.ts

- fixed race condition in getInstance call causing multiple FFmpeg workers to be generated leading to tab crash
- changed thumbnail generation timestamps attempts to 1st video sec and 0th video second.
- tested the changes 
- ran sample dataset upload test

Fix ffmpeg related issue

---

public/locales/en/translation.json
src/components/Collections/CollectionShare/publicShare/manage/linkExpiry.tsx
src/components/DialogBox/base.tsx
src/components/ExportFinished.tsx
src/components/ExportModal.tsx
src/components/Sidebar/ShortcutButton.tsx
src/components/pages/dedupe/SelectedFileOptions.tsx
src/components/pages/gallery/SelectedFileOptions.tsx
src/utils/collection/index.ts
src/utils/number/format.ts
src/utils/time/format.ts

Add Number formatting, to display numbers with language-specific separators.
tested locally

Add number formatting

---

src/components/DialogBox/base.tsx

Fix UI issue caused by emotion migration 
- remove dialog button having an unneeded left margin
tested locally

fix ui issues

---

src/components/Upload/UploadProgress/index.tsx
src/components/Upload/Uploader.tsx
src/services/upload/uiService.ts
src/services/upload/uploadManager.ts
src/services/upload/uploadService.ts

- handle the unhandled exception thrown because of an un-awaited promise
- fixed  issue with upload cancel not clearing the local pending upload list properly 
- Fixed issue: if the user goes from the gallery to another page (let's say dedupe) mid-upload, then the upload progress dialog is dismissed but the upload keeps happening in the background.
- Changed default Behaviour 
upload progress bar will now start minimized until the user manually expands it 
tested locally

fix Upload issues

---

src/components/PhotoViewer/index.tsx

- copy the image to clipboard was getting triggered when the info bar was opened, preventing from copy text from info bar
tested locally

fix Photoviewer issue 

---

src/services/upload/thumbnailService.ts

added actual file size while reporting a large thumbnail-generated warning 
tested locally

add more info to thumbnail_too_large logs

---

src/components/Collections/CollectionShare/publicShare/EnablePublicShareOptions.tsx
src/components/Collections/CollectionShare/publicShare/manage/index.tsx
src/components/PasswordStrength.tsx
src/components/TwoFactor/InvalidInputMessage.tsx
src/components/Upload/UploadProgress/styledComponents.tsx
src/themes/colors/fixed.ts
src/themes/palette/dark.tsx
src/themes/palette/light.tsx
src/themes/types.ts

renamed confusion theme colours names. 
warning meant red and caution meant yellow, 
renaming them to danger for red and warning for yellow 
tested locally

Rename confusing color names

---

src/components/Collections/CollectionCard.tsx
src/components/pages/gallery/PreviewCard.tsx

static image thumb
loading thumb 
fixed preview card static thumbnail colour.
tested locally

Add static thumb to collection cards

---

src/services/upload/exifService.ts

Found images where the camera has stored the date in local time without providing an offset, so safer to just assume that the time is local time. This will be correct for most people unless travelling across timezones
tested locally and added the file to the sample dataset

revert offset handling

---

src/components/Login.tsx
src/pages/_app.tsx
src/pages/change-password/index.tsx

- starting using loading overlay to prevent unmounting root component on page change 
- remove navigation logic in the login component causing unneeded navigation
- fixed issue found while testing, change password didn't have a back button
- tested loading overlay acting as expected
- tested issue fix

Improve load experience 

---

src/constants/upload/index.ts
src/services/upload/exifService.ts
src/utils/error/index.ts

Got some errors on sentry related to exif data parsing falling for `bmp` file, which doesn't have EXIF data, so added them to the `exifless_format` list.
Also, got invalid data from EXIF causing parsing failure. improved  invalid data checks to handle them
- tested with sample dataset 
- tested EXIFLESS_FORMATS are getting skipped properly

improve exif parsing and error handling 

---

src/services/upload/exifService.ts

EXIF data may not have the `GPSLatitudeRef` or `GPSLongitudeRef` if they correspond to positive location values.
handling it by removing the not null check from `GPSLatitudeRef` while parsing the location 
- added a sample file with missing `GPSLatitudeRef` in the sample dataset

Handle location missing GPSLatitudeRef and/or GPSLongitudeRef

---

src/components/Sidebar/HelpSection.tsx
src/constants/redirects/index.ts
src/pages/_app.tsx
src/utils/billing/index.ts

In the case of `families` portal, we generate the link after getting a JWT token from the server. (async call), causing  the `window.open` call **not** being made just after (in the same tick) the user presses the button, but after some interval.
The browser thinks that this is a random popup we are trying to open without any user input and blocks it.
What I have done for now is that instead of trying to fetch the token and then redirecting the user to the link in a new tab.
I redirect him to the static link `web.ente.io?redirect=familes` and the web app which opens on that page, fetches the token and then redirects to the family portal URL.
tested locally

handle popup warning 

---

src/components/GalleryEmptyState.tsx
src/components/PhotoFrame.tsx
src/pages/deduplicate/index.tsx
src/pages/gallery/index.tsx
src/pages/shared-albums/index.tsx

Empty screen for dedupe page missing empty state message
Refactored EmptyState logic out of `PhotoFrame` component, preventing the unwanted effect of changes done for the gallery page affecting other pages 
- tested normal and empty state for gallery and dedupe and shared-albums page

Fix empty screen dedupe

---

src/services/collectionService.ts

Fixes issue in testing introduced by https://github.com/ente-io/photos-web/pull/1092/commits/f173525995385d405ddc5cf3392ac5d346bea8c8 
add a check to prevent reading `favorites` name from `collectionSummary` in case it is removed from the list, for if it was empty 
tested locally

fix favorite name undefined issue 

---

apps/photos/src/constants/redirects/index.ts

- The desktop app is currently opening the roadmap link in an electron window.
Changing the redirection root URL to `https://web.ente.io` to force opening the link in external browser 
tested locally

Open roadmap in browser (desktop)

---

apps/photos/src/components/PhotoList.tsx

^ title 
tested locally by uploading a file multiple copies, some with hash and some without hash

Fix grouping based on hashes on dedupe page 

---

apps/photos/src/components/Upload/Uploader.tsx
apps/photos/src/pages/deduplicate/index.tsx
apps/photos/src/pages/gallery/index.tsx
apps/photos/src/services/collectionService.ts
apps/photos/src/utils/collection/index.ts

- added `getLatestCollections`  as a wrapper to pass the `includeHidden` prop
- avoid using hidden collections as replacement album 
- fixed shared files were shown on the search screen.
tested locally

Update create albums behaviour

---

apps/photos/src/components/pages/gallery/PreviewCard.tsx
apps/photos/src/services/downloadManager.ts
apps/photos/src/services/publicCollectionDownloadManager.ts

- added support to check if the file has a disk Cached thumbnail and show it instead of the scroll placeholder.
- Also removed the thumbnail download rate limiter.
The downloadManager and public DownloadManager can be merged...most of the stuff in them are similar will only difference being the API. Will do this in a future PR to keep this one clean 
tested with gallery and shared-albums files

Show disk cached thumb on scroll

---

apps/photos/src/themes/index.ts

Firefox doesn't support `:has`  pseudo selector so this fix doesn't work https://github.com/ente-io/photos-web/pull/1117
For now, delaying the end animation to 300ms  (default 178ms) seems to have done the trick and Jishnu and I both are now not able to reproduce the issue.
tested by jishnu

Fix  opacity 0% backdrop blocking ui for firefox

---

apps/photos/src/components/Collections/CollectionListBar/index.tsx
apps/photos/src/components/PhotoViewer/FileInfo/RenderCaption.tsx
apps/photos/src/components/PhotoViewer/FileInfo/RenderCreationTime.tsx
apps/photos/src/components/PhotoViewer/FileInfo/RenderFileName.tsx
apps/photos/src/pages/gallery/index.tsx
apps/photos/src/services/collectionService.ts
apps/photos/src/services/fileService.ts
apps/photos/src/services/updateCreationTimeWithExif.ts
apps/photos/src/services/upload/magicMetadataService.ts
apps/photos/src/types/file/index.ts
apps/photos/src/utils/collection/index.ts
apps/photos/src/utils/file/index.ts
apps/photos/src/utils/magicMetadata/index.ts

- renamed `updateMagicMetadataProps` to `updateMagicMetadata` (better name as we are updating the complete  `MagicMetadata` not just the `MagicMetadataProps`)
- Updated `updateCollectionMagicMetadata` to accept `collections` and `updatedMagicMetadata` instead of a collection with updated Magic Metadata.
- Updated `updateFileMagicMetadata` and `updateFilePublicMagicMetadata` similarly to accept file and `updateFileMagicMetadata` instead of the `updatedFiles`

Improve update magic metadata functions

---

apps/photos/src/components/Upload/Uploader.tsx
apps/photos/src/pages/gallery/index.tsx
apps/photos/src/services/collectionService.ts
apps/photos/src/utils/collection/index.ts

- updated the `createAlbum` function to remove the dedupe logic
- created new `getOrCreateAlbums` util to handle the upload use case
- tested creating album to add flow, new album properly created
- tested creating album for upload flow, it's properly deduping and uploading to existing collection if it exists.

remove dedupe logic while creating new collection for add or move 

---

apps/photos/src/components/Collections/index.tsx
apps/photos/src/components/pages/gallery/SelectedFileOptions.tsx
apps/photos/src/pages/gallery/index.tsx

- Fix Add to Collection in search mode, not showing the collection in which the user was when he initiated the search. 
- Fix after adding to the collection in search mode, it was updating the search result header to the collection header of that collection 
tested locally

Fix add to collection in search mode

---

apps/photos/src/constants/upload.ts

HEVC video type was failing, added it to whitelisted formats
tested locally

Add hevc video to whitelisted formats

---

apps/photos/src/components/Notification.tsx

The notification was not showing the correct colour.
tested by checking the subscription update notification

Fix notification color

---

apps/photos/public/locales/en/translation.json
apps/photos/src/components/Collections/CollectionSelector/index.tsx
apps/photos/src/components/Upload/Uploader.tsx
apps/photos/src/components/pages/gallery/SelectedFileOptions.tsx
apps/photos/src/constants/collection.ts
apps/photos/src/types/gallery/index.ts
apps/photos/src/utils/collection/index.ts

fixes #1178
- refactor `openCollectionSelectorFor` logic (by adding intent value)
- added support to upload to the uncategorised album
- show uncategorized album at the start for the upload selector screen.
tested locally

Allow uploads to uncategorized 

---

apps/photos/src/components/SingleInputForm.tsx
apps/photos/src/pages/recover/index.tsx
apps/photos/src/pages/two-factor/recover/index.tsx

- add a new `disableAutoComplete` prop to `singleInputField` component, which can be passed as true to prevent caching values.
For example in the case of `recoveryKey` verify page
tested locally

Add option to prevent Input field caching

---

apps/photos/src/components/PhotoViewer/index.tsx

videos kept playing even when a user went to the next file, fixes the issue, by pausing the video on navigation trigger
tested locally

Pause video on navigate

---

apps/photos/src/constants/upload.ts

- added `CRW`, `ORF` and `RAF` to file types to missed file formats

Add missed file formats to  WHITELISTED_FILE_FORMATS

---

apps/photos/src/pages/gallery/index.tsx

Fixed empty gallery state  shown instead of shared files, when the user has only shared files  
tested locally

Fix empty state with shared files

---

apps/photos/src/components/Collections/AllCollections/index.tsx
apps/photos/src/components/Collections/CollectionListBar/CollectionCard.tsx
apps/photos/src/components/Collections/CollectionListBar/index.tsx
apps/photos/src/components/Collections/index.tsx
apps/photos/src/components/PhotoFrame.tsx
apps/photos/src/components/PhotoList.tsx
apps/photos/src/components/PhotoViewer/FileInfo/index.tsx
apps/photos/src/components/Search/SearchBar/index.tsx
apps/photos/src/components/Search/SearchBar/searchInput/index.tsx
apps/photos/src/components/Sidebar/ShortcutSection.tsx
apps/photos/src/components/pages/gallery/Navbar.tsx
apps/photos/src/components/pages/gallery/PreviewCard.tsx
apps/photos/src/components/pages/gallery/SelectedFileOptions.tsx
apps/photos/src/pages/deduplicate/index.tsx
apps/photos/src/pages/gallery/index.tsx
apps/photos/src/pages/shared-albums/index.tsx
apps/photos/src/types/gallery/index.ts

renamed the existing `activeCollection` state that refers to the active collection id to `activeCollectionID` 
and moved the `activeCollection` state from collections component to gallery 
tested locally

refactored active collection state 

---

apps/photos/src/components/PhotoFrame.tsx
apps/photos/src/pages/gallery/index.tsx

- don't trigger select all, if any modals are open
- don't trigger select all, if the user is typing in an input field 
- Added keyboard shortcut to clear selection with `esc` 
tested locally

Fix select all issue

---

apps/photos/src/components/Upload/Uploader.tsx

Drag and drop to active album was failing for case where the album was not owned by the user
Added is-self-owned album check before uploading to active album
tested locally

fix drag and drop upload issue

---

apps/photos/src/components/pages/dedupe/SelectedFileOptions.tsx

Have for now, just removed the option to toggle club by capture time
will remove and cleanup the code later on.
earlier 
updated
tested locally

remove club by capture time option [dedupe screen] 

---

apps/photos/src/services/export/index.ts
apps/photos/src/services/export/migration.ts
apps/photos/src/types/electron/index.ts
apps/photos/src/utils/error/index.ts

- Changed flow to first update export record update and then attempt export and add rollback logic if export fails 
- Fixed the issue of the metadata folder not being existing for export. 
- Added auto-retry logic to getExportRecord function, which waits for 1 sec and retries to get the export record file, to avoid temporary file read issues. 
- tested export sync operations 
- tested migration

Fix export rename issue

---

apps/photos/src/services/updateCreationTimeWithExif.ts
apps/photos/src/services/upload/exifService.ts
apps/photos/src/services/upload/metadataService.ts
apps/photos/src/utils/ffmpeg/index.ts
apps/photos/src/utils/time/index.ts
apps/photos/tests/upload.test.ts

During Date time parsing, the dimension in the filename got parsed as a time value. (in filename -`2019-07-16-111843_1366x768_scrot.png`)
- Added better date validation  
- Refactored code 
- renamed `getUnixTimeInMicroSeconds` to `validateAndGetCreationUnixTimeInMicroSeconds` and added extra validation that creation time can't be in future 
tested with user-given files

Fixed date time parsing

---

apps/photos/src/pages/_app.tsx
apps/photos/src/pages/auth/index.tsx
apps/photos/src/pages/change-password/index.tsx
apps/photos/src/pages/credentials/index.tsx
apps/photos/src/pages/deduplicate/index.tsx
apps/photos/src/pages/gallery/index.tsx
apps/photos/src/pages/recover/index.tsx
apps/photos/src/pages/two-factor/verify/index.tsx
apps/photos/src/pages/verify/index.tsx
apps/photos/src/services/InMemoryStore.ts
apps/photos/src/services/userService.ts

- Adding lock while configuring SRP, to prevent multiple  simultaneous execution
- removed `redirectURL` state from `appContext` and moved to `inMemoryStore`, as it is not involved with UI, possibly was triggering app refresh 
tested locally

Fix multiple SRP setup issue

---

apps/photos/src/components/Collections/CollectionShare/publicShare/EnablePublicShareOptions.tsx
apps/photos/src/services/downloadManager.ts
apps/photos/src/services/electron/ffmpeg.ts
apps/photos/src/services/electron/fs.ts
apps/photos/src/services/export/index.ts
apps/photos/src/services/importService.ts
apps/photos/src/services/watchFolder/watchFolderService.ts

`window` was getting imported inside a `worker`
replaced usage of `window` with `globalThis` to make it worker-safe
tested locally ml working properly

Fix ml issue

---

apps/photos/src/components/Sidebar/Preferences/index.tsx

- made `advanced` section the last item , seems like a better place 
- Having expandable items at the end seems more visually stable

reorder preference options

---

apps/photos/src/pages/shared-albums/index.tsx

- redirected direct of `albums.ente.io` open without query params and key to `ente.io`
tested locally

Redirect album.ente.io blank open to ente.io

---

apps/photos/src/utils/photoFrame/index.ts

1. cleared video after use to prevent memory issues
2. improve handling by attaching an event listener to "error" too
3. consider video with length zero as unable playable
tested locally

Improve is-playback-possible logic

---

apps/photos/src/services/watchFolder/watchFolderService.ts

missed to remove the allElectronAPIExists(default set to `false`) check from the watch folder functions and hence nothing got disabled.
I removed the check to fix the issue.

Fix watch folder refactoring issue

---

apps/photos/package.json
yarn.lock

Fixes #1190
- Tested locally and verified that we can view existing heic files.
- Verified that thumbnail generation and viewing the original file worked as expected for the file attached in the linked ticket.

Upgrade heic-convert to ^2.0.0

---

apps/photos/src/components/pages/gallery/PlanSelector/card/free.tsx
apps/photos/src/components/pages/gallery/PlanSelector/card/index.tsx

Show manage family portal option if add-on is active

---

apps/photos/src/components/pages/gallery/PreviewCard.tsx

fixes #1559
^ title 
tested locally

Display full name of file and collection on hover

---

apps/photos/public/locales/en/translation.json
apps/photos/src/components/PhotoViewer/ImageEditorOverlay/CropMenu.tsx
apps/photos/src/components/PhotoViewer/ImageEditorOverlay/FreehandCropRegion.tsx
apps/photos/src/components/PhotoViewer/ImageEditorOverlay/TransformMenu.tsx
apps/photos/src/components/PhotoViewer/ImageEditorOverlay/index.tsx
apps/photos/src/constants/photoEditor.ts

Addresses https://github.com/ente-io/photos-desktop/issues/300
* Adds a new "Crop" tab in the photo editor
* Allows users to drag and resize the cropping region
* Scales the crop region accordingly with the full-sized image

Freehand photo editor cropping mode

---

apps/photos/src/components/Upload/Uploader.tsx
apps/photos/src/utils/collection/index.ts

^ title
fixes the issue, of upload resuming when the user has selected uncategorized as the target collection, it creates a new album named "uncategorized"
tested locally

Allow using uncategorized as replacement album

---

apps/photos/src/pages/gallery/index.tsx

^ title 
- now user stays in the origin collection even after the collection operation is completed including unhide photos
fixes #1554 
tested locally

Remain in the same collection during move operation

---

apps/photos/src/components/PhotoFrame.tsx
apps/photos/src/components/PhotoViewer/index.tsx
apps/photos/src/pages/gallery/index.tsx
apps/photos/src/utils/file/index.ts

- tempDeletedFileIds and tempHiddenFileIds are used to keep track of files that are deleted/hidden in the current session but not yet synced with the server.
added temp to name for clarity 
tested locally

Better named react states

---

apps/photos/tests/zip-file-reading.test.ts

These functions (e.g. getElectronFilesFromGoogleZip) look to have been moved from `importService` to `ElectronAPIs` in commit 86d61060b752b2c68e8eabd58cb6ec45c4637175, perhaps the test did not get updated.
Verified that the test runs now from the desktop app.

Fix the zip file related tests

---

scripts/deploy.sh

This backports [#1599](https://github.com/ente-io/photos-web/pull/1599) into the auth-release branch, so that we can deploy the auth app from the same CF pages project without doing a full release.
(It wasn't clear to me how to backport this, I wrote my notes on this here - https://mrmr.io/n/cherry-pick-pr)

Deploy auth from the same repository (#1599)

---

scripts/deploy.sh

...in the photos-web CF pages project.
See the included comment for why this workaround is needed.

Set the correct Sentry tag when deploying auth-release

---

packages/shared/next/next.config.base.js

The reason why Sentry was not showing sourcemaps was because the release value used by the Sentry Webpack plugin at buildtime (autogenerated) was different from the release value that Sentry.init at runtime (git SHA).

Fix sourcemaps association

---

apps/accounts/src/pages/passkeys/flow/index.tsx

I'm not sure if this was intentional, but it looks like the initialization of `pkg` was accidentally deleted in e3019b6a40cea841270124effe9ebcbb35c1f263.

Reintroduce perhaps accidentally deleted line related to passkeys

---

.gitignore

Prune down the gitignore list to the remove gitignored files that were needed at some point, but are not needed now.
@ua741 @httpjamesm this might require you to run `git clean -dxf` on your local checkout once, since you might have leftover files from earlier (they'll not get recreated after this point)

Further prune .gitignore

---

package.json
packages/eslint-config/index.js
packages/eslint-config/package.json
yarn.lock

This was likely happening because the package versions in the top level package.json and the eslint-config package.json were different. I've synced them for now.
> On a longer time frame, the idea is not have such conflicting cases, and remove mostly all the top level package.json dependencies and for the rest rely on them solely being in the top level package.json and not duplicated in two places.
Since the eslint plugin version was updated, there were some new warnings that I had to temporarily suppress.
Before this change, the following (arbitrary package) install was failing
yarn workspace photos add -D @emotion/babel-plugin
It works afterwords.

Fix `yarn workspace photos add foo`

---

apps/photos/src/components/pages/gallery/PreviewCard.tsx
packages/shared/next/next.config.base.js

This workaround was added in https://github.com/ente-io/photos-web/pull/1027,
but it has stopped working again, likely due to the update to Next 14. We're
only using nested child selectors in one place (not 100% sure of this, but I did
try to poke around and verify that statement a bit).
This was causing an error in dev mode, and silent failure in production mode.
- Hover state is restored
- dev mode seems to work fine
- yarn build also works

Remove the need for nested child selectors to workaround emotional (sic) issues

---

apps/accounts/package.json
apps/auth/package.json
apps/cast/package.json
apps/photos/package.json
docs/dev.md
package.json
packages/accounts/package.json
packages/build-config/package.json
packages/shared/package.json
packages/utils/.prettierrc.json
yarn.lock

https://github.com/simonhaenisch/prettier-plugin-organize-imports
Also move the remaining dev dependencies down to the leaf instead of in the global package.json. This PR should prepare the ground, in the next PR I intend to do the migration to Prettier defaults.

Add prettier-plugin-organize-imports
