- src/pages/credentials/index.tsx
- src/pages/generate/index.tsx
- src/types.ts
- src/utils/crypto/libsodium.ts
- src/worker/crypto.worker.js
To be merged only after Version 150 of frame is live on both AppStore and PlayStore.
> Use sensitive ops and mem limits to derive key

- src/components/PhotoFrame.tsx
- src/components/SearchBar.tsx
- src/pages/gallery/index.tsx
- src/utils/search/index.ts
It removes stats for time being. Will look into how we can resurface that.
> Fix search issue.

- src/pages/credentials/index.tsx
- src/pages/verify/index.tsx
- src/services/userService.ts
- src/utils/crypto/index.ts
> Revert " 2fa "

- src/components/NavigationButton.tsx
- src/components/PhotoFrame.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/Collections.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/types.ts
Gallery will now adjust to occupy the entire screen space. It supports dynamic columns and also merges multiple dates in the same row for large displays.
Everything is parameterized. :bowtie:
> Responsive gallery on steriods

- src/components/ChangeEmail.tsx
- src/components/EnteCard.tsx
- src/components/ExportModal.tsx
- src/components/Sidebar.tsx
- src/pages/_app.tsx
- src/pages/change-email/index.tsx
- src/services/userService.ts
- src/utils/strings/englishConstants.tsx
> Change email

- src/components/ChangeEmail.tsx
- src/components/icons/ExpandLess.tsx
- src/components/icons/ExpandMore.tsx
- src/components/pages/gallery/AlertBanner.tsx
- src/components/pages/gallery/LinkButton.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/components/pages/gallery/Upload.tsx
- src/components/pages/gallery/UploadProgress.tsx
- src/pages/_app.tsx
- src/services/uploadService.ts
- src/utils/common/errorUtil.ts
- src/utils/common/index.ts
- src/utils/strings/englishConstants.tsx
> Update upload result UI

- src/components/Sidebar.tsx
- src/utils/strings/englishConstants.tsx
> Add delete account button on sidebar

- src/pages/verify/index.tsx
- src/utils/strings/englishConstants.tsx
Test Plan: Tested this on my local machine.
> Show correct err msg when verification code has expired

- src/components/FullScreenDropZone.tsx
- src/components/icons/MoveIcon.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/pages/gallery/index.tsx
- src/services/collectionService.ts
- src/utils/collection/index.ts
- src/utils/common/errorUtil.ts
- src/utils/strings/englishConstants.tsx
Move files between collections 
Move icon hidden on All section
Also hide the collection from which the files are moved in the collection Selector list
> Move files

- src/components/pages/gallery/CollectionSelector.tsx
> dont justify Collection Selector items

- src/components/Container.ts
- src/components/icons/SortIcon.tsx
- src/components/icons/TickIcon.tsx
- src/components/pages/gallery/CollectionOptions.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/CollectionSort.tsx
- src/components/pages/gallery/CollectionSortOptions.tsx
- src/components/pages/gallery/Collections.tsx
- src/components/pages/gallery/LinkButton.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/pages/gallery/index.tsx
- src/services/collectionService.ts
- src/utils/collection/index.ts
- src/utils/strings/englishConstants.tsx
Adds Collection sort button with three sorting options
1. most recent photo
2. last modified 
3. album title
Selected option is highlighted and has a tick mark
> Sort collections

- src/components/SearchBar.tsx
- src/components/icons/CollectionIcon.tsx
- src/components/pages/gallery/Collections.tsx
- src/pages/gallery/index.tsx
- src/services/searchService.ts
adds search collection by name option
https://user-images.githubusercontent.com/46242073/134642071-6e79cf44-d491-4070-ae45-98b8ed849a9a.mov
> Search collection

- src/components/icons/MoveIcon.tsx
> update move icon

- src/pages/gallery/index.tsx
archive section now have the URL -> `/gallery/collection=archive`
tried switching between collection and checking error logs
> updates archive collection URL

- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/pages/gallery/index.tsx
- src/services/collectionService.ts
- src/utils/collection/index.ts
- src/utils/sentry/index.ts
- Removes Move option from favorite collection
- fix sorting to have favorite collection at the front
- fix error handling while sorting
> Fix favorite collection behavior

- src/services/collectionService.ts
- src/utils/sentry/index.ts
> Sort explosion fix

- src/components/pages/gallery/SelectedFileOptions.tsx
added delete option when files in archive are selected
updated
> add delete option for archived files

- src/utils/strings/englishConstants.tsx
> Ensure consistency in strings with the mobile app

- src/components/Container.ts
- src/components/FullScreenDropZone.tsx
- src/components/PhotoFrame.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/SearchBar.tsx
- src/components/Sidebar.tsx
- src/components/icons/Archive.tsx
- src/components/icons/CollectionIcon.tsx
- src/components/icons/MoveIcon.tsx
- src/components/icons/SortIcon.tsx
- src/components/icons/TickIcon.tsx
- src/components/icons/UnArchive.tsx
- src/components/pages/gallery/CollectionOptions.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/CollectionSort.tsx
- src/components/pages/gallery/CollectionSortOptions.tsx
- src/components/pages/gallery/Collections.tsx
- src/components/pages/gallery/LinkButton.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/pages/gallery/index.tsx
- src/services/collectionService.ts
- src/services/fileService.ts
- src/services/searchService.ts
- src/utils/collection/index.ts
- src/utils/common/errorUtil.ts
- src/utils/file/index.ts
- src/utils/sentry/index.ts
- src/utils/strings/englishConstants.tsx
- src/worker/crypto.worker.js
- Move Files 
- archive files
- hide shared album files from all Section
- shared album files can't be added to or moved to other albums
- sort collections
- search collection by name
- Fix refresh stop sync
- don't justify Collection Selector items
tested all the feature and disabled network to test failure scenarios
> September Release 

- src/services/fileService.ts
^title
clearLocalDB and resynced checked file count, its equal to fileCount in the details API response
> update to collection diff v2

- src/components/PhotoFrame.tsx
- src/components/pages/gallery/PreviewCard.tsx
select a pic then pressing shift and moving highlights the photos in range...clicking on a photo then select all the photos in the range
> Range select

- src/services/upload/exifService.ts
- src/services/upload/metadataService.ts
^ title
testing locally with sample files
> send fileType info with exif data missing logs

- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
> fixed install mobile app banner not shown on empty screen

- src/components/PhotoFrame.tsx
- src/components/pages/gallery/PreviewCard.tsx
range select was disabled when two items selected before trying to range select
> range-select fixes

- src/services/fileService.ts
> fix file not found chrome error

- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/icons/TickIcon.tsx
- src/components/pages/gallery/CollectionSortOptions.tsx
- src/pages/_app.tsx
- src/services/fileService.ts
> Update change creation time UI

- src/pages/gallery/index.tsx
- src/utils/strings/englishConstants.tsx
> Empty trash changes

- src/components/EnteSpinner.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/RecoveryKeyModal.tsx
- src/pages/_app.tsx
- src/services/fileService.ts
- src/utils/file/index.ts
- src/utils/strings/englishConstants.tsx
> Update file name

- public/.well-known/apple-app-site-association
> host apple-app-site-association file

- public/.well-known/apple-app-site-association
> hostapple-app-site-association file

- public/.well-known/assetlinks.json
> Andoird digital asset linking

- public/robots.txt
> Allow bots to parse .well-known directory

- public/.well-known/assetlinks.json
> Add digital assetlink for android

- src/services/ffmpegService.ts
- src/services/upload/queueProcessor.ts
- src/utils/common/errorUtil.ts
> bubble up error to caller from queue processor

- package.json
- src/components/RecoveryKeyModal.tsx
- src/pages/recover/index.tsx
- src/pages/two-factor/recover/index.tsx
- yarn.lock
Title ^
Verified that
- For same account, the web showed same 24 letter recovery code as on mobile.
- Able to recover account using 24 word mnemonic recovery key
- Able to recover account using old recovery code (bin2hex value)
> Add support to show mnemonic recovery key

- src/pages/gallery/index.tsx
- src/services/searchService.ts
- src/utils/file/index.ts
- filtered out trashed files from  search results
- fixes search showing nothing when there was no location search result
> Remove trashed files from search results

- src/services/upload/thumbnailService.ts
^ earlier fixed this in PR  #220 , missed one place
already tested in perv PR
> missed a place where type info was not logged

- src/components/PhotoFrame.tsx
- yarn.lock
- Gallery loads in a weird way for uncached files
monkey tested and  the issues can't be replicated
> fixes photoswipe issues

- src/components/icons/DownloadIcon.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/pages/gallery/index.tsx
- src/services/downloadManager.ts
- src/utils/file/index.ts
add download option for  selected files
> Download selected

- src/services/userService.ts
> Enable batch edit of creation-time for 243

- src/components/pages/gallery/CollectionOptions.tsx
- src/components/pages/gallery/Collections.tsx
- src/pages/gallery/index.tsx
- src/utils/collection/index.ts
- src/utils/strings/englishConstants.tsx
Give option to download all files of a album.
tested by downloading few albums, with varying count of files
> Download album

- src/components/EnteDateTimePicker.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
missed loading animation to submit button of change creation time. Looked like nothing happened on submitting
added the animation  
https://user-images.githubusercontent.com/46242073/148329604-30d6b404-35ad-4c53-bc68-ff5c31bb04a3.mov
tested locally
> add loading spinner during creation udpate api call

- src/components/FixCreationTime/index.tsx
- src/components/PhotoFrame.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/PreviewCard.tsx
1. the overlapping end item gets deselected
2. the count of selected items becomes incorrect
https://user-images.githubusercontent.com/46242073/148341249-a29dcdf6-2c8b-4f1b-9443-e75ebc604f21.mov
tested locally
https://user-images.githubusercontent.com/46242073/148350074-1d3cd77b-96f5-4c1a-b887-6bba4a1918cf.mov
> Fix overlapping range select behaviour 

- configUtil.js
- next.config.js
- tsconfig.json
`_header` file added only set headers for hosted version so local running apps miss the headers and FFmpeg is not working locally.
This sets headers for the local development apps 
also minor refactoring of `next.config.js` file
tested by checking that the headers are set properly and the app builds properly
> Configure local headers

- src/components/PhotoSwipe/PhotoSwipe.tsx
^title
tested locally when file EXIF reading failed due to unknown file format.
the error was handled and didn't leak to global error handler
> handle exifr parsing failure gracefully

- src/services/exportService.ts
- src/services/upload/metadataService.ts
- src/services/upload/uploadService.ts
- src/services/upload/uploader.ts
- src/types/file/index.ts
- src/types/upload/index.ts
- src/utils/export/index.ts
- src/utils/upload/index.ts
^title
the app is building successfully
> Rename type MetadataObject to Metadata

- src/services/upload/metadataService.ts
- src/services/upload/readFileService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploadService.ts
- src/types/upload/index.ts
fix casing of variable and its type  from `parsedMetaDataJSON` to `parsedMetadataJSON`
the app builds successfully after refactoring
> Fix casing

- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/Upload.tsx
^ title
missed this in #286 
tested locally
> use suggested name if available during first upload

- src/components/PhotoFrame.tsx
> fix search count by updating it when filteredData changes 

- src/pages/404.tsx
- src/utils/strings/englishConstants.tsx
> add 404 page

- src/components/PhotoSwipe/PhotoSwipe.tsx
^title 
locally tested
for both edit name and date
> disable edits for shared collections

- sentry.client.config.js
- src/components/PhotoFrame.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/pages/_app.tsx
- src/pages/credentials/index.tsx
- src/pages/gallery/index.tsx
- src/services/billingService.ts
- src/services/downloadManager.ts
- src/services/upload/exifService.ts
- src/utils/common/apiUtil.ts
change of `Url`  to `URL`
app is building successfully.
> Change url casing

- src/components/pages/gallery/UploadProgress.tsx
- src/constants/upload/index.ts
- src/services/upload/uploader.ts
- src/utils/strings/englishConstants.tsx
> fix file too large description

- sentry.client.config.js
- src/components/PhotoFrame.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/pages/_app.tsx
- src/pages/credentials/index.tsx
- src/pages/gallery/index.tsx
- src/services/billingService.ts
- src/services/downloadManager.ts
- src/services/upload/exifService.ts
- src/utils/common/apiUtil.ts
copy of change URL casing  #315 
---
merged the last commit to sharable-url PR by mistake
> change url casing 

- src/components/RecoveryKeyModal.tsx
- src/utils/crypto/index.ts
> better handle if getRecoveryKey fails

- configUtil.js
> disable report for local csp

- src/components/RecoveryKeyModal.tsx
automatically close recovery modal only on error 
broke in  #320
tested locally is bar pakka 😅
> fix recovery modal not opening

- src/services/downloadManager.ts
- src/services/userService.ts
- src/utils/storage/localForage.ts
- handle cache failure in incognito mode
- use the default driver option for local-forage -  [ indexedDB, WebSQL, localStorage,] 
tested locally on firefox
> Incognito mode usage

- src/components/Sidebar.tsx
please don't kill me 🙏 
update the error dialog message style for when get recovery code fails
tested locally
> update error dialog style shown for get recovery code failure

- src/components/pages/gallery/UploadProgress.tsx
- src/constants/upload/index.ts
- src/services/upload/uiService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploadService.ts
- src/services/upload/uploader.ts
- src/utils/strings/englishConstants.tsx
no need to set finished file's progress, as they are moved to a result list and not shown in the in-progress section anymore anyways
> upload progress bar upload

- src/components/Navbar.tsx
- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/components/pages/gallery/LinkButton.tsx
- src/components/pages/sharedAlbum/GoToEnte.tsx
- src/pages/_app.tsx
- src/pages/shared-albums/index.tsx
- src/types/publicCollection/index.ts
- src/utils/collection/index.ts
- src/utils/publicCollectionGallery/index.ts
- src/utils/strings/englishConstants.tsx
- positioned GoToEnte button on the navbar 
- made report button - into a link 
- changed button text for web
tested locally
> Public album styling

- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/RecoveryKeyModal.tsx
- src/components/SearchBar.tsx
- src/pages/gallery/index.tsx
- src/pages/shared-albums/index.tsx
- src/services/publicCollectionDownloadManager.ts
- src/services/publicCollectionService.ts
- src/utils/file/index.ts
minor fixes for unrelated multiple found bugs 
tested each of them separately while fixing
> Bug fix public sharing

- src/components/CollectionShare.tsx
- src/components/PhotoList.tsx
- src/components/pages/sharedAlbum/AbuseReportForm.tsx
- src/components/pages/sharedAlbum/CollectionInfo.tsx
- src/components/pages/sharedAlbum/GoToEnte.tsx
- src/pages/_app.tsx
- src/pages/gallery/index.tsx
- src/pages/index.tsx
- src/pages/shared-albums/index.tsx
- src/services/publicCollectionDownloadManager.ts
- src/services/publicCollectionService.ts
- src/utils/strings/englishConstants.tsx
> Sharable url patches

- src/components/CollectionShare.tsx
- src/pages/index.tsx
- src/pages/shared-albums/index.tsx
- src/utils/strings/englishConstants.tsx
> Styling and string sharable url

- src/pages/gallery/index.tsx
- src/pages/shared-albums/index.tsx
- src/services/collectionService.ts
- src/services/publicCollectionService.ts
- src/types/collection/index.ts
- src/utils/error/index.ts
- fix loading bar not working
- parse error better
- remove `validTill` and `deviceLimit` and let server set default values 
- use `collectionKey-accessToken` as collectionUID to prevent using previous `shareURL` saved files for a collection if accessToken changes
tested locally the changes
> Public url final touchup

- src/components/pages/sharedAlbum/AbuseReportForm.tsx
- src/utils/strings/englishConstants.tsx
> Update report abuse strings

- src/services/HEICConverter.ts
- src/services/queueProcessor.ts
- src/services/upload/thumbnailService.ts
- src/services/upload/uploadManager.ts
- src/utils/comlink/index.ts
- src/utils/crypto/index.ts
- src/utils/file/convertHEIC.ts
- src/utils/file/index.ts
- src/worker/convert.worker.js
- src/worker/crypto.worker.js
created a new `convert worker` to handle the conversion,
the  file decryption was blocking the conversion when using the same worker for both
tested by viewing the shared-album , the conversion was happening correctly
> Convert worker

- src/components/pages/sharedAlbum/AbuseReportForm.tsx
- src/pages/index.tsx
- src/pages/shared-albums/index.tsx
- src/utils/strings/englishConstants.tsx
- Update the report form message 
- Fixed back button not working problem
- update empty screen message  to with  👀 wla message
checked each of them locally
> Public link updates

- src/components/PhotoList.tsx
- src/constants/publicCollection/index.ts
- src/utils/strings/englishConstants.tsx
> update albums footer

- sentry.client.config.js
- src/components/PhotoList.tsx
- src/constants/sentry/index.ts
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/services/publicCollectionDownloadManager.ts
see individual commit messages
tested locally
> Public url bug fixes

- src/components/PhotoList.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/services/downloadManager.ts
- src/services/publicCollectionDownloadManager.ts
- src/utils/error/index.ts
- src/utils/strings/englishConstants.tsx
- add checks to throw an error if resp data is `undefined` and prevent storing it in cache
- update style of the footer
- add CF worker to set meta description tag
> fixes caching 

- src/services/publicCollectionService.ts
> remove token and key logging

- src/components/Container.ts
- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/pages/sharedAlbum/GoToEnte.tsx
- src/constants/publicCollection/index.ts
- src/constants/urls/index.ts
- src/services/publicCollectionDownloadManager.ts
- fix video loading
- fix hash when `photoswipe` opened
- fix file info UI
- hide file info option for shared albums
- change shared URL hook button to go to ente.io
tested locally
> Public link changes

- src/pages/shared-albums/index.tsx
- src/services/publicCollectionService.ts
> update publicCollectionUID template

- package.json
- src/pages/shared-albums/index.tsx
- src/utils/collection/index.ts
- yarn.lock
> Release base58

- src/utils/file/index.ts
^title
tested locally by exporting a live photo and a normal image file
> download live photo assets seperately

- configUtil.js
- public/_headers
updates
- enable CSP for the local environment so they are quickly noticed and can fix them then
- updated CSP for prod with needed values found during testing (add media-src manifest src )
- allowed  local server as connect-src  in the local CSP 
checked 
- tested the local server calls are working 
- media and manifest are not blocked
> CSP update

- README.md
the submodule pull command in the readme doesn't work
My bad should have been caught in the review
tested that the new command is working
> fix submodule pull command

- src/pages/shared-albums/index.tsx
- src/services/publicCollectionService.ts
- src/utils/strings/englishConstants.tsx
See individual commit
Tested locally
> Minor bug fixes in shared album

- configUtil.js
set to report only to fix some issues before inforcing them, some cases have not been handled that are breaking the uploads and downloads
also re-setup reporting to the CSP endpoint.
> local csp update

- public/_headers
> fix malformated csp directive

- configUtil.js
- public/_headers
- sentry.client.config.js
- src/components/PhotoFrame.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/pages/credentials/index.tsx
- src/pages/shared-albums/index.tsx
- src/services/publicCollectionDownloadManager.ts
- src/services/publicCollectionService.ts
- src/types/collection/index.ts
- src/types/publicCollection/index.ts
- src/utils/file/index.ts
- src/utils/publicCollectionGallery/index.ts
- src/utils/strings/englishConstants.tsx
This change adds support for viewing password-protected album links. 
- Verified that we are able to open password-protected links
- Verified that password prompt doesn't come up if the link is not password protected.
> add support for showing password protected albums

- configUtil.js
- public/_headers
- sentry.client.config.js
- src/components/PhotoFrame.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/pages/credentials/index.tsx
- src/pages/shared-albums/index.tsx
- src/services/publicCollectionDownloadManager.ts
- src/services/publicCollectionService.ts
- src/types/collection/index.ts
- src/types/publicCollection/index.ts
- src/utils/error/index.ts
- src/utils/file/index.ts
- src/utils/publicCollectionGallery/index.ts
- src/utils/strings/englishConstants.tsx
> Show err for popular albums

- src/pages/shared-albums/index.tsx
- src/services/publicCollectionService.ts
- updated card bottom margin
- fix  `verifyPublicCollectionPassword` fail error message
verified the changes
> Sharable url password entry UI

- src/constants/upload/index.ts
- src/services/ffmpegService.ts
- src/services/updateCreationTimeWithExif.ts
- src/services/upload/exifService.ts
- src/services/upload/metadataService.ts
- src/services/upload/videoMetadataService.ts
- src/types/upload/index.ts
- src/utils/time/index.ts
- src/utils/upload/index.ts
- use FFmpeg to extract global video metadata
- also extracted location when available (found it in Apple photos exported video files)
-  tested on the set of sample videos
> Ffmpeg video metadata

- src/components/PhotoFrame.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/services/fileService.ts
- src/services/trashService.ts
- src/services/upload/uploadManager.ts
- src/utils/file/index.ts
- fix video loader not showing up issue
- add top loader for file loading
> Fix loading

- src/components/FailedUploads.tsx
- src/components/Sidebar.tsx
- src/components/pages/gallery/UploadProgress.tsx
- src/services/upload/uploadManager.ts
- src/utils/storage/localStorage.ts
- logged failed files to local DB
- add sidebar button and dialog to show failed files
tested locally
> Log failed files

- src/components/Sidebar.tsx
- src/utils/storage/index.ts
> Update styles for the debug logs button

- src/utils/storage/index.ts
- fix keep newer logs(last 1000 items)  and discard older ones 
- tested on console
> fix keep newer logs

- src/services/upload/fileService.ts
- src/services/upload/thumbnailService.ts
- src/services/upload/uploadManager.ts
> verbose logs

- src/components/PhotoFrame.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/components/pages/gallery/PreviewCard.tsx
- avoid creating deep copies of files
tested locally
> fix lagging issue

- src/services/upload/uploadManager.ts
- src/services/upload/uploader.ts
- src/utils/upload/index.ts
> Support for preserving iCloud Album structure

- src/constants/upload/index.ts
- src/services/typeDetectionService.ts
- src/services/upload/thumbnailService.ts
- src/utils/file/index.ts
- yarn.lock
- skipped jpeg extension type detection
- updated type-detection library to the latest version
- there was a webm type detection issue which is fixed in the latest version so updated the library
tested locally
> Skip jpeg type detection

- src/constants/upload/index.ts
- src/services/typeDetectionService.ts
- src/services/upload/thumbnailService.ts
- src/utils/file/index.ts
- yarn.lock
Reverts ente-io/bada-frame#435
> Revert "Skip jpeg type detection"

- src/pages/shared-albums/index.tsx
- src/services/publicCollectionDownloadManager.ts
- src/services/publicCollectionService.ts
- don't send an empty jwt token
- better  logs
tested locally
> Fix manage sharable url

- src/components/PhotoFrame.tsx
- src/pages/_app.tsx
- yarn.lock
- disabled right-click for images and videos
- refactored styling 
- tested for image , video and live photo and when video plays fails
> Improve disable download

- package.json
- src/components/pages/gallery/UploadProgress.tsx
- src/services/upload/uploadManager.ts
- src/services/upload/uploader.ts
- yarn.lock
- add wait time after running uploader, so that  garbage collection  can run and UI can be updated
- update uploadProgress modal to handle very quick item changes
tested locally
> fix page unresponsive during upload

- README.md
> Shoutout to browserstack

- src/components/FileList.tsx
- src/components/pages/gallery/UploadProgress.tsx
use react-window list for upload progress bar lists
> react-window progress bar list

- src/components/PhotoFrame.tsx
- src/components/PhotoSwipe/PhotoSwipe.tsx
- src/components/pages/gallery/CollectionOptions.tsx
- src/components/pages/gallery/Collections.tsx
- src/constants/file/index.ts
- src/pages/gallery/index.tsx
- src/services/collectionService.ts
- src/services/fileService.ts
- src/services/updateCreationTimeWithExif.ts
- src/types/collection/index.ts
- src/types/file/index.ts
- src/types/magicMetadata/index.ts
- src/utils/collection/index.ts
- src/utils/file/index.ts
- src/utils/magicMetadata/index.ts
- src/utils/strings/englishConstants.tsx
- support archiving albums
- show  albums as archives on the web that are from mobile
tested locally
> Archive albums

- src/services/billingService.ts
Title ^
Discovered this while I am reviewing the usage of endpoints related to billing and usage.
> yarn dev
> remove unused method 

- src/components/pages/gallery/PreviewCard.tsx
- src/pages/deduplicate/index.tsx
- src/services/deduplicationService.ts
- src/types/deduplicate/index.ts
- added collection and file name
- added sorting logic
> Dedupe improvements

- src/utils/time/index.ts
missed the case where the file name didn't have any numbers in it 
handled it by adding  null checks 
tested locally
> added better null checks

- src/services/importService.ts
fix backward compatibility issues 
missed checks for whether API is present or not at some places
> add missing checks before using newer APIs

- src/components/MessageDialog.tsx
- src/components/pages/gallery/Upload.tsx
- src/components/pages/gallery/UploadProgress.tsx
- src/pages/gallery/index.tsx
- src/utils/common/deviceDetection.ts
- src/utils/common/index.ts
- src/utils/strings/englishConstants.tsx
- src/utils/upload/isCanvasBlocked.ts
- added logic to detect canvas is blocked and show a message with desktop app download link
> Handle blocked canvas

- src/components/Sidebar.tsx
- src/components/pages/gallery/PlanSelector.tsx
- src/pages/_app.tsx
- src/services/billingService.ts
- src/services/userService.ts
- src/types/user/index.ts
- src/utils/billing/index.ts
- src/utils/common/apiUtil.ts
- src/utils/storage/localStorage.ts
- src/utils/strings/englishConstants.tsx
> Family Plan

- src/components/PhotoFrame.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/utils/error/index.ts
PR https://github.com/ente-io/bada-frame/pull/493 , rebased on release
> Release fix file undefined error

- src/utils/common/apiUtil.ts
> update family portal url

- public/robots.txt
> Resolve release merge conflict

- src/services/trashService.ts
^title
tested deleting files and syncing trash, everything is working file
> move to trash v2 api

- src/pages/_app.tsx
- src/services/userService.ts
get URL from backend,  redirect on client-side
tested locally
> roadmap v2

- src/pages/_app.tsx
This fixes redirection getting terminated with NS_ABORTED error because another page change was triggered
> prevent route change if redirection requested

- src/components/MessageDialog/index.tsx
- src/themes/darkThemeOptions.tsx
> Message dialog redesign v1

- src/components/pages/gallery/Upload.tsx
Fixes the type error caused when starting the app on older desktop versions.
Tested locally using an older version.
> Check if newer electron APIs exist for pending uploads

- src/services/upload/uploadManager.ts
added logs for 
- complete upload breaking
- and for post upload task  
tested the logs have stacktrace
> Upload logs

- src/services/fileService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploader.ts
more logs to help with debugging and logged the data saved into local DB 
tested locally the log entry are as excepted and upload also doesn't have a issue
> Debug logs for invalid blob error

- src/services/upload/livePhotoService.ts
- src/services/upload/metadataService.ts
- src/types/upload/index.ts
- src/utils/crypto/index.ts
- src/utils/crypto/libsodium.ts
- src/utils/upload/index.ts
> Added file hashing

- src/services/upload/fileService.ts
- src/services/upload/metadataService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploadService.ts
- src/utils/crypto/index.ts
- Tested it generates same hash.
> Use getFileStream instead of file.stream

- src/components/pages/gallery/PreviewCard.tsx
- src/constants/upload/index.ts
- src/services/typeDetectionService.ts
- src/services/upload/metadataService.ts
add mod file format to the exception list https://www.online-convert.com/file-format/mod
> Fix file type detection

- src/constants/upload/index.ts
- src/services/typeDetectionService.ts
- src/services/upload/metadataService.ts
> Release fix file type detection

- src/components/pages/gallery/SelectedFileOptions/DeduplicateOptions.tsx
- src/pages/deduplicate/index.tsx
- src/services/deduplicationService.ts
- src/types/deduplicate/index.ts
- src/utils/strings/englishConstants.tsx
- Tested that only files with same file hashes are being grouped and shown
> Dedupe using file hash

- src/pages/_app.tsx
use Map instead of an object to store redirection paths to avoid Unvalidated dynamic method call
tested locally redirection are working
> fix code scan issue-1

- src/components/pages/gallery/PreviewCard.tsx
> fix file name overlay to expand to full width of the image

- src/components/PhotoFrame.tsx
- src/pages/deduplicate/index.tsx
^ title
tested locally on the library where issue was detected
> add isDeduplication property to avoid hiding archived files

- src/services/ffmpeg/ffmpegClient.ts
- src/services/heicConverter/heicConverterClient.ts
- src/services/migrateThumbnailService.ts
- src/services/readerService.ts
- src/services/typeDetectionService.ts
- src/services/updateCreationTimeWithExif.ts
- src/services/upload/fileService.ts
- src/services/upload/livePhotoService.ts
- src/services/upload/metadataService.ts
- src/services/upload/thumbnailService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploadService.ts
- src/services/upload/uploader.ts
- src/utils/crypto/index.ts
- src/utils/file/index.ts
^
- tested with large video
- image
- heic
- live photo
> Move to using arrayBuffer instead of readAsArrayBuffer

- src/components/pages/gallery/SelectedFileOptions/DeduplicateOptions.tsx
- src/pages/deduplicate/index.tsx
- src/services/deduplicationService.ts
- src/types/deduplicate/index.ts
- src/utils/strings/englishConstants.tsx
- Tested locally with some files with and without file hashes.
> Group dedupes by same file hashes when possible

- src/services/userService.ts
^title 
tested locally for non 401 and 401 errors
> return  false  from isTokenValid only if api resonse is 401

- src/services/upload/livePhotoService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploader.ts
filter out files whose metadata detection failed or those that have been skipped because the files are too large,
tested locally by returning null from metadata extraction and checking if upload breaks.
> Fix live photo cluterring

- src/constants/upload/index.ts
- src/services/migrateThumbnailService.ts
- src/services/upload/multiPartUploadService.ts
- src/services/upload/uploadService.ts
^title 
tested locally, direct uploads are happening with flag set to false
> disable cf proxied upload 

- src/components/Collections/AllCollections/CollectionCard.tsx
- src/components/Collections/AllCollections/content.tsx
- src/components/Collections/AllCollections/index.tsx
- src/components/Collections/CollectionBar/ScrollButton.tsx
- src/components/Collections/CollectionBar/index.tsx
- src/components/Collections/CollectionInfo.tsx
- src/components/Collections/CollectionInfoWithOptions.tsx
- src/components/Collections/index.tsx
- src/components/Collections/styledComponents.ts
- src/components/Container.ts
- src/components/PhotoList.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/hooks/useComponentScroll.tsx
- src/pages/gallery/index.tsx
- src/pages/shared-albums/index.tsx
- src/services/collectionService.ts
- src/types/collection/index.ts
- src/utils/file/index.ts
> Collections redesign v2

- src/components/PhotoFrame.tsx
- src/components/Search/SearchResultInfo.tsx
- src/components/Search/index.tsx
- src/components/Search/input.tsx
- src/components/pages/gallery/Navbar.tsx
- src/pages/gallery/index.tsx
- src/types/gallery/index.ts
- src/types/search/index.ts
- src/utils/strings/englishConstants.tsx
> Search result redesign

- src/components/Collections/CollectionBar/index.tsx
- src/components/pages/gallery/CollectionSelector.tsx
- src/services/collectionService.ts
- src/types/collection/index.ts
> Update collection summary

- src/components/pages/gallery/PreviewCard.tsx
> add broder radius to preview card

- src/components/Form/FormContainer.tsx
> Center forms

- src/components/UploadProgress/dialog.tsx
- src/components/UploadProgress/footer.tsx
- src/components/UploadProgress/header.tsx
- src/components/UploadProgress/inProgressSection.tsx
- src/components/UploadProgress/index.tsx
- src/components/UploadProgress/minimized.tsx
- src/components/UploadProgress/progressBar.tsx
- src/components/UploadProgress/resultSection.tsx
- src/components/UploadProgress/title.tsx
- src/components/pages/gallery/Upload.tsx
- src/constants/upload/index.ts
- src/contexts/uploadProgress.tsx
- src/services/upload/uiService.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploader.ts
- src/types/upload/index.ts
- src/types/upload/ui.ts
> add upload progress context

- src/pages/credentials/index.tsx
- src/utils/error/index.ts
- src/utils/strings/englishConstants.tsx
> better password key derivation failed messsage

- src/components/Collections/CollectionBar/ScrollButton.tsx
- src/components/Collections/CollectionBar/index.tsx
- src/components/Collections/CollectionInfoWithOptions.tsx
- src/components/Collections/index.tsx
- src/components/Collections/styledComponents.ts
- src/components/PhotoList.tsx
- src/components/Search/SearchResultInfo.tsx
- src/pages/gallery/index.tsx
- src/pages/shared-albums/index.tsx
- src/types/gallery/index.ts
> Collection title scroll

- package.json
- src/components/Collections/index.tsx
- src/components/Collections/styledComponents.ts
- src/components/Container.ts
- src/components/EnteDateTimePicker.tsx
- src/components/FixCreationTime/options.tsx
- src/components/PhotoList.tsx
- src/components/PhotoSwipe/InfoDialog/RenderCreationTime.tsx
- src/constants/file/index.ts
- src/pages/gallery/index.tsx
- src/utils/collection/index.ts
- src/utils/file/index.ts
- yarn.lock
> Date time picker

- src/utils/billing/index.ts
- src/utils/common/index.ts
>  open family page in new tab

- src/components/Form/ShowHidePassword.tsx
- src/components/Search/SearchBar/searchInput/valueContainerWithIcon.tsx
- src/components/Sidebar/Header.tsx
- src/styles/search.ts
- src/themes/darkThemeOptions.tsx
> Use stroke color icons

- src/components/Container.ts
- src/components/Form/ShowHidePassword.tsx
- src/components/PhotoSwipe/InfoDialog/FileNameEditForm.tsx
- src/components/PhotoSwipe/InfoDialog/RenderCreationTime.tsx
- src/components/PhotoSwipe/InfoDialog/RenderFileName.tsx
- src/components/Sidebar/Header.tsx
- src/components/pages/dedupe/SelectedFileOptions.tsx
- src/components/pages/gallery/SelectedFileOptions.tsx
- src/themes/darkThemeOptions.tsx
> remove custom icon button

- src/pages/deduplicate/index.tsx
> fix back on dedupe screen

- src/components/Collections/AllCollections/CollectionSort/optionCreator.tsx
- src/components/ExportFinished.tsx
- src/components/ExportInProgress.tsx
- src/components/ExportInit.tsx
- src/components/ExportModal.tsx
- src/components/MemberSubscriptionManage.tsx
- src/components/OverflowMenu/option.tsx
- src/components/Sidebar/HelpSection.tsx
- src/components/Sidebar/SubscriptionCard/index.tsx
- src/components/Sidebar/userDetailsSection.tsx
- src/hooks/useLocalState.tsx
- src/pages/gallery/index.tsx
- src/services/exportService.ts
- src/utils/strings/englishConstants.tsx
> Export redesign

- src/components/Collections/CollectionInfo.tsx
- src/components/Collections/CollectionInfoWithOptions.tsx
- src/components/Collections/CollectionListBar/CollectionCard.tsx
- src/components/Collections/CollectionListBar/index.tsx
- src/components/Collections/styledComponents.ts
- src/components/TruncateText.tsx
- src/constants/collection/index.ts
- src/services/collectionService.ts
- src/types/collection/index.ts
- src/utils/collection/index.ts
> Collection bar tile redesign

- src/pages/index.tsx
- src/utils/strings/englishConstants.tsx
> Fix carousel copies

- src/pages/index.tsx
- src/utils/strings/englishConstants.tsx
> update onboarding buttons

- src/components/Upload/Uploader.tsx
- src/pages/index.tsx
- src/utils/strings/englishConstants.tsx
> Fix canvas blocked message dialog

- src/components/Upload/Uploader.tsx
- src/hooks/useFileInput.tsx
- src/pages/index.tsx
- src/utils/strings/englishConstants.tsx
> Fix file picker multiple selection issue

- src/components/pages/gallery/PlanSelector/card.tsx
- src/components/pages/gallery/PlanSelector/card/free.tsx
- src/components/pages/gallery/PlanSelector/card/index.tsx
- src/components/pages/gallery/PlanSelector/card/paid.tsx
- src/components/pages/gallery/PlanSelector/periodToggler.tsx
- src/components/pages/gallery/PlanSelector/plans/planRow.tsx
- src/utils/strings/englishConstants.tsx
> Plan selector UI fixes

- src/components/PhotoSwipe/InfoDialog/ExifData.tsx
- src/components/PhotoSwipe/styledComponents/Pre.tsx
- fixes the button positioning 
- also fixes the formating when showing all EXIF
> update exif show all button

- src/utils/strings/englishConstants.tsx
> update search placeholder text

- src/components/Search/SearchBar/searchBarMobile.tsx
- src/components/Search/SearchBar/styledComponents.tsx
- src/components/Upload/UploadButton.tsx
- src/components/pages/gallery/Navbar.tsx
- src/pages/gallery/index.tsx
- make the gallery navbar transparent and show the app navbar which has centred logo 
- no need to hide the search bar until the load is completed as user can till then search among files loaded files
> Center navbar logo

- src/components/pages/gallery/PlanSelector/card/index.tsx
missed null check 
tested locally
> fix plan selector open on signup

- src/components/EnteLogo.tsx
- src/pages/index.tsx
- src/utils/strings/englishConstants.tsx
height 24 pt
margin bottom 32px
> update carousel title

- src/pages/index.tsx
> Add some padding to the landing page

- src/components/Collections/CollectionShare/emailShare.tsx
- src/components/Collections/CollectionShare/sharees/index.tsx
email share just got faster by 2000ms 🥲
> remove delays added for testing

- src/pages/index.tsx
> directly go to gallery if key present

- src/styles/global.css
https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools#how-to-avoid-showing-invisible-text
tested locally using lighthouse analysis, and 👀
> fix font flicker issue

- src/components/ChangeEmail.tsx
- src/components/Login.tsx
- src/components/SignUp.tsx
- src/pages/verify/index.tsx
- src/services/userService.ts
Tested with a local instance of museum that has the updated endpoint. Will remove this from DRAFT once that is deployed.
> Use the new POST variant of /users/ott

- src/pages/_app.tsx
- src/services/importService.ts
- src/utils/sentry/index.ts
> Ignore unnecessary errors

- src/services/typeDetectionService.ts
https://sentry.ente.io/organizations/ente/issues/2445/?project=2&query=is%3Aunresolved&statsPeriod=14d
added error logs if mime type is missing, wasn't able to replicate the error
hopefully, we will get more logs which will help debug the issues
tested locally, type detection working for image and videos both
> better handle file type detection error 

- src/utils/strings/englishConstants.tsx
fix INSTALL_MOBILE_APP message casing
> fix casing 

- src/pages/gallery/index.tsx
^title 
`text color: secondary`
`font size 14px`
> redesign first load message

- src/components/Sidebar/DebugLogs.tsx
- src/pages/_app.tsx
- src/services/heicConverter/heicConverterService.ts
- src/utils/file/index.ts
add size logs to check if converted file is null / undefined  
tested locally
> Heic preview issue- added size logs 

- src/services/downloadManager.ts
> don't wait on cache put

- src/services/cacheService.ts
- src/services/downloadManager.ts
- src/services/electron/cache.ts
- src/services/electron/common.ts
- src/services/userService.ts
- add cache service to encapsulate different cache providers 
- add cache delete API 
tested locally delete API 
and existing API after refactoring
> Clear disk cache logout

- src/components/Upload/UploadProgress/minimized.tsx
- src/components/Upload/Uploader.tsx
1. refactor some code (comm
2. and remove unnecessary props causing unnecessary confusion (see second [commit message](https://github.com/ente-io/bada-frame/pull/685/commits/e76217a051b0c81d5557253af554365042abc37d)) 
tested locally
> upload related component code quality imporvement 

- src/components/Sidebar/SubscriptionStatus/index.tsx
- src/components/pages/gallery/PlanSelector/card/paid.tsx
- src/utils/strings/englishConstants.tsx
fixes the text was not updating for the subscription cancelled state. 
tested with my personal stripe subscription account
> Fix subscrtiption cancelled state

- src/components/Sidebar/userDetailsSection.tsx
- src/types/user/index.ts
update the user email using the user detail API response 
tested locally
> update user email with the synced user details email

- src/components/PhotoFrame.tsx
- src/services/collectionService.ts
- src/services/upload/uploadManager.ts
- src/utils/file/index.ts
- fix files in multiple collections getting counted in multiple times for archived section count
- moved "all section Files count" deviation logic to getCollectionsFileCount function  
tested locally
> Fix collection file count

- package.json
- src/services/electron/cache.ts
- src/services/electron/common.ts
- src/services/electron/safeStorage.tsx
- src/services/exportService.ts
- src/services/importService.ts
- src/types/electron/index.ts
> Add electron APIs types

- src/components/ExportModal.tsx
- src/services/electron/cache.ts
- src/services/electron/common.ts
- src/services/electron/fs.ts
- src/services/electron/safeStorage.tsx
- src/services/exportService.ts
- src/services/importService.ts
- src/services/watchFolder/watchFolderService.ts
> change case electron instance variable

- src/themes/darkThemeOptions.tsx
update background paper and over paper colors
> update elavation colors

- src/components/Upload/UploadProgress/dialog.tsx
- src/components/Upload/Uploader.tsx
- stale pickedUploadType( set by upload done by clicking the upload button)  getting used for dragAndDrop upload 
- once hasUnUploadedFiles to true, it was never getting cleared
tested locally
> Fix upload issues

- src/components/Upload/Uploader.tsx
- src/components/WatchFolder/index.tsx
- src/components/WatchFolder/mappingEntry/index.tsx
- src/components/WatchFolder/mappingList/noMappingsContent/noMappingsContent.tsx
- src/services/watchFolder/watchFolderService.ts
- src/utils/strings/englishConstants.tsx
- src/utils/upload/index.ts
fixes
- choice modal opening on sidebar open [7a3da0d3df66deca2651031dc0f29d49990a818b]
- font size [bd4b456bd1b466a4be9b5f8b75e536090d778fbe]
- tooltip on mapping icon [2df32ba7f3a726d1db8bb52fb94d4cbef551e8c5]
- ignore system files like (.DS_STORE) during upload [2df32ba7f3a726d1db8bb52fb94d4cbef551e8c5]
tested locally
> Fix watch folder issues

- src/components/Upload/Uploader.tsx
- src/components/WatchFolder/mappingList/noMappingsContent/noMappingsContent.tsx
- src/services/watchFolder/watchFolderEventHandlers.ts
- src/services/watchFolder/watchFolderService.ts
- src/types/watchFolder/index.ts
- src/utils/upload/index.ts
- src/utils/watch/index.ts
fixed reported issues 
tested locally
> fix watch folder issues-2 

- src/services/deduplicationService.ts
> simplify duplicate sorting order to just alphabetical

- src/services/updateCreationTimeWithExif.ts
don't skip fix time for video and live photo if the custom time used
tested locally
> fix time for live-photo and videos

- README.md
* Update the screenshot in the README (had forgotten to update this after the redesigned version had been launched).
* Also add manual line breaks to increasing the spacing above the sections (this matches what is there in the frame README).
> Update the README screenshots

- src/services/billingService.ts
> fix verify susbcription call 

- src/components/DialogBox/base.tsx
- src/components/pages/gallery/PlanSelector/manageSubscription/index.tsx
- src/utils/strings/englishConstants.tsx
> Fix strings and make dialog actions stacked

- src/services/ffmpeg/ffmpegClient.ts
- src/utils/ffmpeg/index.ts
don't use the user filename as an identifier instead generate use datatime string and use that
tested locally
> fix thumbnail generation failure

- src/components/Collections/index.tsx
- src/components/PhotoList.tsx
- src/pages/gallery/index.tsx
- src/utils/collection/index.ts
- all section has nothing to see here yet 
- trash section has the collection bar to navigate back to all section 
tested locally
> Fix all files trashed state

- src/services/fileService.ts
- src/types/file/index.ts
add batching to delete from trash 
tested locally
> Add batching to delete from trash

- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/services/downloadManager.ts
- src/services/publicCollectionDownloadManager.ts
- src/services/queueProcessor.ts
- add queue processor for thumbnail download (maxParellelProcessing =5)
- don't trigger download and show a placeholder Preview when the user is scrolling through gallery 
- reduce extra rows rendered to 1 page of row (both up and down)
tested locally
> Thumbnail scroll

- src/components/Upload/UploadProgress/dialog.tsx
- src/components/Upload/UploadProgress/inProgressSection.tsx
- src/components/Upload/UploadProgress/title.tsx
- src/services/upload/uiService.ts
- src/services/upload/uploadManager.ts
- src/utils/strings/englishConstants.tsx
- metadata extraction files in progress are shown correctly
- other stages state is not affected 
- cancelling upload does lead to a bad state
> Add metadata extraction progress

- src/components/Upload/Uploader.tsx
- src/services/electron/common.ts
- src/services/upload/uploadManager.ts
- src/services/upload/uploader.ts
- src/types/electron/index.ts
- src/utils/logging/index.ts
log to disk if is electron 
tested locally
> Log to disk for electron

- src/components/pages/gallery/PlanSelector/card/index.tsx
- src/utils/billing/index.ts
fix expired non-listed plans shown on the plan screen 
earlier 
fixed 
tested locally
> only add non listed plan user is subscribed to if subscription is active

- src/services/electron/common.ts
> change to globalThis to prevent importing window in worker

- src/services/searchService.ts
don't get location suggestions during the search 
tested locally, 
no API calls for location results are made
> disable location search

- src/utils/strings/englishConstants.tsx
> fix file ID casing

- src/components/WatchFolder/styledComponents.tsx
- src/pages/_app.tsx
- src/themes/darkThemeOptions.tsx
use the MUI colour scheme setting option to change web default components to use dark theme colour 
https://mui.com/material-ui/react-css-baseline/#color-scheme 
https://web.dev/color-scheme/
tested with browser stack on windows (chrome and firefox ) and mac
> Fix scrollbar color

- src/components/Sidebar/DebugLogs.tsx
- src/services/electron/common.ts
- src/types/electron/index.ts
- src/utils/logging/index.ts
completely move to disk logging on electron 
[open-log-directory](https://github.com/ente-io/bhari-frame/pull/84) PR added the API
tested locally
> electron logging improvement

- package.json
- src/utils/export/index.ts
- yarn.lock
use [santize-filename](https://www.npmjs.com/package/sanitize-filename) for santizing filenames
tested locally with Japanese words.
> better Sanitize filename during export 

- src/components/Sidebar/DebugLogs.tsx
- src/constants/logging/index.ts
- src/pages/_app.tsx
- src/utils/logging/index.ts
- src/utils/storage/index.ts
- clear logs if localStorage gets full
tested locally
> delete old logs if local storage is full

- src/utils/storage/localStorage.ts
fixes the error "undefined" is not valid JSON, 
tested locally
> add better invalid JSON data checks

- src/themes/darkThemeOptions.tsx
> update body1 line height

- src/components/DialogBox/DialogIcon.tsx
- src/components/DialogBox/base.tsx
- src/components/DialogBox/index.tsx
- src/components/SingleInputForm.tsx
- src/pages/_app.tsx
- src/services/electron/common.ts
- src/services/electron/update.ts
- src/types/dialogBox/index.ts
- src/types/electron/index.ts
- src/utils/strings/englishConstants.tsx
tested locally that the events are fired, event listeners are listening and opens the update dialog accordingly
and the update-restart call also works properly.
> App Update dialog 

- src/utils/logging/index.ts
> clear logs on QuotaExceededError

- src/components/PhotoFrame.tsx
- src/components/PhotoViewer/InfoDialog/CaptionEditForm.tsx
- src/components/PhotoViewer/InfoDialog/RenderCaption.tsx
- src/components/PhotoViewer/InfoDialog/index.tsx
- src/components/PhotoViewer/index.tsx
- src/constants/file/index.ts
- src/styles/global.css
- src/types/file/index.ts
- src/utils/file/index.ts
- src/utils/strings/englishConstants.tsx
add support to show,add and edit captions
tested locally
> Caption support

- src/components/Badge.tsx
- src/components/PhotoViewer/index.tsx
- src/styles/global.css
- src/themes/darkThemeOptions.tsx
added blur to caption background
tested locally
> Caption background

- src/components/Sidebar/DebugSection.tsx
- src/components/Sidebar/index.tsx
- src/services/electron/common.ts
- src/types/electron/index.ts
checked that it's not shown on the web
> show app version on sidebar for electron

- src/components/PhotoList.tsx
- src/pages/deduplicate/index.tsx
- src/themes/darkThemeOptions.tsx
- added loader while dupes are loaded
- fix all dupes showing up on one row, until window resized
before 
https://user-images.githubusercontent.com/46242073/201266970-d6019b4d-5f7d-4299-be3e-5a0319208e0c.mov
after
https://user-images.githubusercontent.com/46242073/201266985-3b3a3983-f307-47fa-880c-5ee74c781ed5.mov
> Loader for dedupe screen

- sentry.client.config.js
- sentry.server.config.js
wrap set user in async block as getSentryID is now a promise
tested locally
> fix-uncaught-expection-missing-user id 

- src/services/exportService.ts
- src/utils/export/index.ts
YOLO. Will test before next release.
> Export caption in the sidecar file

- src/pages/recover/index.tsx
- src/pages/two-factor/recover/index.tsx
> trim whitespace between words in recovery key

- src/components/Collections/CollectionShare/publicShare/manage/linkExpiry.tsx
- src/components/ExportFinished.tsx
- src/components/PhotoList.tsx
- src/components/PhotoViewer/InfoDialog/RenderCreationTime.tsx
- src/components/PhotoViewer/InfoDialog/index.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/utils/export/index.ts
- src/utils/file/index.ts
- src/utils/logging/index.ts
- src/utils/strings/englishConstants.tsx
- src/utils/time/format.ts
- src/utils/time/index.ts
update time formatting to follow Figma styles
checked locally, all instances of formatted time have been updated
> Time formatting 

- src/components/PhotoViewer/FileInfo/index.tsx
- check undefined before looping out map entry 
tested locally
> fix file info issue

- src/components/PhotoFrame.tsx
- src/components/PhotoViewer/FileInfo/index.tsx
- src/components/PhotoViewer/index.tsx
- src/pages/deduplicate/index.tsx
- src/services/downloadManager.ts
- src/services/publicCollectionDownloadManager.ts
- src/services/updateCreationTimeWithExif.ts
- src/types/file/index.ts
- src/types/gallery/index.ts
- src/utils/file/index.ts
add checks to prevent re-running of checkExifAvailable util and thereby changing of EXIF state and hence the re-renders
tested locally
> Fix view exif flicker issue

- src/components/PhotoViewer/index.tsx
- src/services/exportService.ts
- src/services/publicCollectionService.ts
remove debugging console logs 
> remove console logs

- src/pages/gallery/index.tsx
- src/services/userService.ts
> malformed keys

- src/components/PhotoFrame.tsx
Fixes The live photo preview that broke while I was making the info screen change, 
tested locally
> fix live-photo preview

- README.md
Only README was touched, so didn't do any tests.
> Change bhari-frame => photos-web in README etc

- src/components/Collections/AllCollections/CollectionSort/options.tsx
- src/constants/collection/index.ts
- src/services/collectionService.ts
- remove sort by newest option from collection sort options 
- added migration to update existing collection sort from newest to last updated.
> remove sort by newest option

- src/components/SingleInputForm.tsx
- src/components/Upload/Uploader.tsx
- src/components/UserNameInputDialog.tsx
- src/utils/strings/englishConstants.tsx
tested locally the count is shown correctly
> Add photo count public upload

- src/components/Collections/CollectionShare/publicShare/manage/index.tsx
- src/components/Collections/CollectionShare/publicShare/manage/publicCollect.tsx
- src/utils/strings/englishConstants.tsx
checked enabling and disabling works
> reenable public collect manage option

- src/components/Upload/Uploader.tsx
- src/constants/upload/index.ts
- src/types/upload/index.ts
- src/utils/strings/englishConstants.tsx
- src/utils/ui/index.tsx
- src/utils/upload/index.ts
folder + files drop and selecting the  create separate collections for each folder  option leads to an underminable state for where the files should be uploaded 
added a dialog to tell the user about it 
tested locally
> fix upload behavior

- src/services/upload/fileService.ts
add pubMagicMetadata not undefined encryption check before trying to encrypt it
tested locally
> fix non-public collection upload

- src/components/Sidebar/SubscriptionCard/contentOverlay/family/usageSection/progressBar.tsx
- src/components/Sidebar/SubscriptionCard/contentOverlay/individual/usageSection.tsx
- src/utils/billing/index.ts
- fixes when usage is less than zero, the subscription card was showing undefined
- add checks to prevent more than 100% usage 
tested locally
> fix nan undefined shown on storage card

- src/components/PhotoViewer/FileInfo/RenderFileName.tsx
- src/components/PhotoViewer/FileInfo/index.tsx
- src/components/PhotoViewer/index.tsx
- fixes live photo and video  icon 
- fixes EXIF extraction failure which caused infinite spinner
tested locally
> Fix file info issues

- src/services/upload/hashService.tsx
- src/utils/error/index.ts
added file chunk count less than expected count check 
testing pending
> Add file chunk count check

- src/components/Upload/Uploader.tsx
- src/pages/shared-albums/index.tsx
- src/services/upload/uploadManager.ts
- src/services/upload/uploadService.ts
fix publicUploadProps not getting updated when password jwt token  Changes by adding it to `uploadManager` init dependency
> fix password locked public collection upload

- src/styles/search.ts
- src/utils/strings/englishConstants.tsx
- fixes cursor positioning on the search bar
- and removed the location from the placeholder text
tested locally
> fix search bar style and placeholder

- src/components/Collections/CollectionSelector/index.tsx
fix null check on `onCancel` callback for `collectionSelector` 
tested locally
> fix collection selector close

- src/components/Collections/index.tsx
- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/components/pages/gallery/Navbar.tsx
- src/pages/gallery/index.tsx
- src/services/searchService.ts
- src/utils/file/index.ts
- fixes shared albums not showing in the search result
- fixes collection with no unique files not showing up in search result
- fixes collection header not resetting after search close
- show search results without change to all section
- fixes files with creationTime as zero causing a crash
- tested the fixes
- tested that trash files are shown in the result
> Fix search issues

- src/components/Collections/CollectionInfoWithOptions.tsx
- src/components/Collections/CollectionListBar/CollectionCard.tsx
- src/components/Collections/CollectionOptions/AlbumCollectionOption.tsx
- src/components/PhotoViewer/FileInfo/RenderCaption.tsx
- src/components/PhotoViewer/FileInfo/RenderFileName.tsx
- src/components/PhotoViewer/FileInfo/index.tsx
- src/components/PhotoViewer/index.tsx
- src/components/Sidebar/ShortcutSection.tsx
- src/components/Titlebar.tsx
- src/pages/shared-albums/index.tsx
- src/utils/ui/index.tsx
import just the icon instead of complete package
tested locally
> fix dev high memory usage 

- src/components/PhotoList.tsx
> remove testing console logs

- src/pages/gallery/index.tsx
the preloading of the image was blocked on sync to complete 
tested locally
> fxi subscription card background late load

- .husky/pre-commit
fixes https://github.com/okonet/lint-staged/issues/1064
tested on Anand's system
> run precommit hook with yarn

- .husky/pre-commit
- src/components/Collections/CollectionListBar/CollectionCard.tsx
Add icon to shared album
Tested Locally
> Add icon to shared album

- src/components/Collections/CollectionOptions/SharedCollectionOption.tsx
- src/components/Collections/CollectionOptions/index.tsx
- src/constants/collection/index.ts
- src/services/collectionService.ts
- src/utils/strings/englishConstants.tsx
Add delete option to shared album
> Add delete option to shared album

- src/utils/common/apiUtil.ts
configured staging deployment connect to the staging server.
So that jishnu can test flows on staging environment.
- tested that the normal and public uploads and  normal file/thumbnail and public-file/public-thumbnail download are working properly.  
- confirmed that non-staging deployment connect to production server
> configure api util for staging

- src/services/exportService.ts
- src/types/electron/index.ts
updated the Electron API `saveStreamToDisk` type.
> update saveStreamToDisk Api type and usage

- src/components/Sidebar/ThemeSwitcher.tsx
- src/components/Sidebar/UtilitySection.tsx
- src/constants/theme/index.ts
- src/pages/_app.tsx
- src/themes/lightThemeOptions.tsx
- src/types/theme/index.ts
- src/utils/strings/englishConstants.tsx
- src/utils/user/index.ts
Introduced new light theme option and added option to enable it [for internal user's only]
checked that option only shown for internal users
> Light mode

- src/components/PhotoFrame.tsx
- src/services/downloadManager.ts
- src/services/publicCollectionDownloadManager.ts
> add ui logs

- src/components/Collections/CollectionListBar/CollectionCard.tsx
- src/components/Collections/CollectionOptions/index.tsx
- src/constants/collection/index.ts
- src/services/collectionService.ts
Collection Action for Collection Shared With me Shown for Shared by me collections too
create a separate type for shared by me (outgoing share) and shared with me (incoming share)
- checked incoming and outgoing share have respective correct options
> Fix Collection Action for shared collections

- next.config.js
- src/utils/common/apiUtil.ts
- src/utils/storage/localStorage.ts
- forward node layer IS_TEST_RELEASE environment variable to web app 
- added option to set API endpoint in local storage
tested locally
> testing setup

- src/services/electron/common.ts
- src/types/electron/index.ts
> integrate log renderer process memory usage api

- src/components/Collections/index.tsx
- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/pages/gallery/index.tsx
- src/pages/shared-albums/index.tsx
- src/utils/storage/localStorage.ts
> Fix state memory leaks

- src/components/Sidebar/SubscriptionCard/contentOverlay/storageSection.tsx
- src/utils/billing/index.ts
fixes Storage was shown 1 unit more than it was.
tested locally
> fix storage card rounding issue

- src/components/PhotoViewer/index.tsx
add proper file and not checks.
testing locally
> fix file undefined error 

- src/themes/darkThemeOptions.tsx
- src/themes/lightThemeOptions.tsx
switch light mode and dark mode backdrop main colour
> fix popular chip color

- src/components/CodeBlock/styledComponents.tsx
- src/components/Collections/CollectionInfoWithOptions.tsx
- src/components/Collections/CollectionShare/publicShare/control.tsx
- src/components/PhotoViewer/index.tsx
- src/components/SingleInputForm.tsx
- src/pages/deduplicate/index.tsx
- src/themes/darkThemeOptions.tsx
- fix dialog backdrop shadow issue
- clear add email share input field after adding the sharee
- [fix copy button positioning and double hover background issue](https://github.com/ente-io/photos-web/pull/898/commits/bb79e5faaebc09a976871a093882698be8e7c5e3)
- [fix dedupe again showing no dedupe text before remote fetch](https://github.com/ente-io/photos-web/pull/898/commits/f2601d6b1729a2dd203147958e5e4ca43af6421e)
- [fix downloadFile and copy to clipboard helper](https://github.com/ente-io/photos-web/pull/898/commits/de20ab2cc659535f4ea456c2f52025de43ba4ab4)
- [fix collection not updated after creating public URL (syncWithRemote silently after URL creation)](https://github.com/ente-io/photos-web/pull/898/commits/05abff83a754132559b119e712d1d303632332a5)
- [remove trash and archived …
> Fixing testing reported issues

- src/services/collectionService.ts
- src/services/fileService.ts
clear last sync time of a collection after it has been deleted 
tested locally
> fix sync for reshared album 

- src/services/electron/imageProcessor.ts
- src/services/upload/thumbnailService.ts
- src/utils/error/index.ts
> updated native image processor error handling

- src/components/Collections/CollectionShare/emailShare.tsx
- src/components/PhotoViewer/index.tsx
- src/components/SingleInputForm.tsx
- input field error not shown 
- handle uncaught expections 
tested locally and confirmed with jishnu
> fix testing reported issues

- src/services/collectionService.ts
- src/utils/collection/index.ts
- check if target collection is a valid move target 
- confirmed that it fixes the jishnu issue
> Fix uncategoried issue

- src/components/PhotoFrame.tsx
- src/components/PhotoList.tsx
- src/components/PhotoViewer/index.tsx
- src/components/pages/gallery/PreviewCard.tsx
- src/pages/gallery/index.tsx
- src/services/collectionService.ts
- src/services/fileService.ts
- src/services/trashService.ts
- src/services/upload/uploadManager.ts
- src/types/gallery/index.ts
- src/utils/collection/index.ts
- src/utils/file/index.ts
- src/utils/photoFrame/index.ts
- rafactored photoframe 
- prevent updation of files state and did all updates on the photoFrame component
- simplified `mergeMetadata`, `sortFiles` 
- removed preservePhotoSwipeProps
- preview card working properly,
- check scrolling through the gallery doesn't cause re-render
- sync doesn't cause renderers
- range select and normal select works
- it updates the file properly
- in range select and select on click works
> Fix chrome possible out of memory warning

- src/components/PhotoFrame.tsx
- src/utils/photoFrame/index.ts
> Fix unhandled error

- src/components/PhotoList.tsx
- src/components/pages/gallery/PreviewCard.tsx
-  fix the thumbnail preview not showing after the scroll stop 
- added missing key 
- fixed setting id instead of key 
> Fix preview card issue

- src/components/PhotoFrame.tsx
- src/components/pages/gallery/PreviewCard.tsx
- fixed accessing id of undefined (user variable )
- disabled file selection for public link 
tested locally
> Fix public link

- src/services/fileService.ts
- src/utils/file/index.ts
the sorting needs to be based on creation time, and for the same creation time, modification time should be used to compare files 
tested locally
> fix sorting

- README.md
Also reduce verbosity in the CTA to star.
> Add translation instructions

- src/services/downloadManager.ts
- added support to override token and worker used in download Manager
- also added support to pass timeout to Axios request
> Download manager ML support Changes

- .gitmodules
> change submodule URL to https version

- package.json
- src/services/machineLearning/machineLearningService.ts
- src/utils/machineLearning/visualization.ts
- yarn.lock
remove unused `tsne-js` package 
fixes 
- https://github.com/ente-io/photos-web/security/dependabot/27
- https://github.com/ente-io/photos-web/security/dependabot/26
- https://github.com/ente-io/photos-web/security/dependabot/25
- https://github.com/ente-io/photos-web/security/dependabot/24
- checked app building properly
-  smoke tested the ml features and  to confirm that, it's running without any errors
> Fix security warning 27

- package.json
- yarn.lock
- updated next/bundle-analyzer package to latest version.
it is used to determine the bundle of the app...
Its just a dev-dependency,so just confirmed that the build, is working fine.
> Fix security warning 19

- src/components/Search/SearchBar/searchInput/index.tsx
- src/services/searchService.ts
- src/types/search/index.ts
- src/utils/strings/englishConstants.tsx
^ title 
tested caption search for existing and new captions
> add caption search support

- src/utils/strings/englishConstants.tsx
> fix caption search copy

- package.json
- src/components/Collections/CollectionShare/publicShare/manage/selectComponents/LabelWithDivider.tsx
- src/components/DialogBox/DialogIcon.tsx
- src/components/Search/SearchBar/searchInput/valueContainerWithIcon.tsx
- src/components/Sidebar/Preferences/LanguageSelector.tsx
- src/components/Sidebar/Preferences/index.tsx
- src/components/Sidebar/UtilitySection.tsx
- src/constants/locale/index.ts
- src/pages/_app.tsx
- src/themes/darkThemeOptions.tsx
- src/themes/lightThemeOptions.tsx
- src/utils/storage/index.ts
- src/utils/storage/localStorage.ts
- src/utils/strings/englishConstants.tsx
- src/utils/strings/frenchConstants.tsx
- src/utils/strings/index.ts
- src/utils/strings/vernacularStrings.ts
- yarn.lock
on desktop 
on web 
https://user-images.githubusercontent.com/46242073/222167789-c4d41bf2-86c1-406c-882e-de1367287fbd.mov
> Language change setting

- src/constants/api/index.ts
- src/constants/file/index.ts
- src/services/collectionService.ts
- src/services/fileService.ts
- src/utils/common/index.ts
- added batching to APIs which have batch limit on server
> Add API batching 

- src/components/ExportModal.tsx
- src/services/exportService.ts
add logs around export progress to see where the issue related to the export file count may be 
tested the logs locally.
> Add export logs

- src/utils/strings/frenchConstants.tsx
Some lines are not "translatable" in git
> 1st french adjusts

- public/locales/en/translation.json
- src/components/ExportModal.tsx
- src/services/exportService.ts
- src/types/electron/index.ts
- src/types/export/index.ts
- src/utils/collection/index.ts
- src/utils/export/index.ts
- added wrapper folder for export (ente Photos)
- added ability to open the export folder by clicking on Folder Field 
- lazily create collection folders 
https://user-images.githubusercontent.com/46242073/227139250-be47cf92-191e-4fcd-a9ac-e67f5c497aee.mov
tested locally
> Export improvements

- src/components/ExportModal.tsx
fixes 
- fix async `exportStage` updates, getting triggered in wrong order causing export State get set as the wrong value, used export service, `exportInProgress` flag to correct it. 
- fix folder change useEffect
tested changes locally
> Fix export issues

- .github/workflows/codeql-analysis.yml
- src/pages/auth/index.tsx
- src/pages/credentials/index.tsx
- used setRedirectURL to handle redirection after login for auth page , to avoid https://github.com/ente-io/photos-web/security/code-scanning/4
- updated code QL action to run for PR based on main, instead of master.
tested locally
> fix client side redirection warning

- src/services/upload/multiPartUploadService.ts
- src/services/upload/uploadService.ts
- fixed  fetchMultipartUploadURLs for public upload, we were attempting to get normal multipart URLs for Public upload.
tested by uploading sample dataset on public upload
> fix multi-part public upload

- src/components/Upload/Uploader.tsx
- Collection create dialog with pre-filled name, will be shown, instead of automatically creating a collection with folder name when user clicks on upload to new collection
https://user-images.githubusercontent.com/46242073/231670683-5b8e9ed7-d93c-4526-b7b5-92ef37df4fab.mov
tested locally
> Update upload ux 

- src/components/SetPasswordForm.tsx
- src/components/SignUp.tsx
added show password option to one password field on signup form and change password form 
tested locally
> Add show password option

- src/components/Collections/CollectionNamer.tsx
- src/components/PhotoViewer/FileInfo/FileNameEditDialog.tsx
- src/components/SetPasswordForm.tsx
- src/components/SignUp.tsx
updated create album dialog and file name edit dialog to use dialogBoxV2 component, to fix the spacing issue, between buttons 
> Update dialogs to dialogBoxV2

- src/pages/gallery/index.tsx
- src/services/userService.ts
- deregister event listener and clearInterval for  syncing with Remote on logout 
tested locally
> fix session expired message shown during login flow 

- src/components/pages/auth/Navbar.tsx
> Redesign Auth Page 

- src/components/Collections/CollectionCard.tsx
- fixed null check before trying to access file object property 
tested locally
> fix collection card expection

- src/themes/palette/index.tsx
> fixed ui issue

- src/components/Collections/CollectionSelector/index.tsx
- src/components/Navbar/SelectionBar.tsx
- src/components/Upload/Uploader.tsx
- Sorted Collection by name in collectionSelector screen  
- Fix the Selection bar hidden behind the navbar 
- Fix upload progress not shown issue  
tested locally
> Fix UI issues

- src/components/Collections/CollectionShare/publicShare/switch.tsx
> fix radio button background

- src/services/upload/exifService.ts
handle EXIF dates of format `YYYYDDMM` 
tested locally
> Improve exif date parsing

- src/components/PhotoViewer/FileInfo/index.tsx
- Fixed the issue of undefined being rendered as location even when exif had location info
tested locally
> Fix exif location rendering issue 

- public/locales/en/translation.json
- src/components/Sidebar/Preferences/LanguageSelector.tsx
- src/constants/locale/index.ts
- src/services/collectionService.ts
- src/utils/i18n/index.ts
- Added Spanish Language option 
- Added logic to translate `uncategorized` collection and `favorite` collection names on UI
tested locally
> Spanish language option

- src/components/PhotoViewer/FileInfo/index.tsx
> ignore (0,0) location data

- src/components/Upload/Uploader.tsx
intercept drag and drop and check if the file is zip then try reading zip content.
- tested by uploading test zip dataset
- tested normal upload
> Handle zip drop on desktop

- next.config.js
- package.json
- src/pages/_error.tsx
- src/utils/sentry/index.ts
- yarn.lock
Fix issue where some uncaught exceptions were not passed to the sentry by nextJS and hence reported. 
- added custom NextJS _error page to page these errors to sentry.
- Upgraded to the latest sentry 
tested locally that uncaught expectation are properly reported
> Fix sentry not reporting client side exception

- apps/photos/src/services/export/index.ts
- apps/photos/src/services/export/migration.ts
- show export as running while the migration is running 
- fix missing throw error 
- minor refactoring and code cleanup 
tested locally
> fix export migration issue

- apps/photos/src/components/ExportModal.tsx
- apps/photos/src/pages/_app.tsx
- apps/photos/src/services/export/index.ts
- apps/photos/src/services/export/migration.ts
- apps/photos/src/services/queueProcessor.ts
- apps/photos/src/utils/error/index.ts
- Fix export cancellation not working issue
tested locally and verified by jishnu
> Fix Export cancellation issue

- apps/photos/src/themes/components.ts
use the suggested https://github.com/mui/material-ui/issues/32286#issuecomment-1287951109 patch until the issue is fixed
tested locally
> Fix Modal not dismounted on close but stuck open at 0% opacity

- apps/photos/package.json
- apps/photos/src/components/Collections/AllCollections/collectionCard.tsx
- apps/photos/src/components/Collections/AllCollections/content.tsx
- apps/photos/src/components/Collections/AllCollections/dialog.tsx
- apps/photos/src/components/Collections/CollectionCard.tsx
- apps/photos/src/components/Collections/CollectionListBar/CollectionCard.tsx
- apps/photos/src/components/Collections/CollectionListBar/index.tsx
- apps/photos/src/hooks/useComponentScroll.tsx
- apps/photos/src/pages/gallery/index.tsx
- yarn.lock
- Used react window to render only in-view collection cards in collection bar and All Collection Dialog
-  updated scroll to collection logic to work with react window 
- tested locally by setting the collection list to have 800 items
> Fix renderer crash

- apps/photos/src/constants/upload/index.ts
- apps/photos/src/services/typeDetectionService.ts
- apps/photos/src/utils/error/index.ts
- whitelisted dv and WMV formats
- added sample dv and WMV file to the sample dataset
- tested with sample files an
> Old formats support

- apps/photos/src/components/FixCreationTime/index.tsx
- apps/photos/src/components/FixLargeThumbnail.tsx
- apps/photos/src/components/PhotoList.tsx
- apps/photos/src/services/downloadManager.ts
- apps/photos/src/services/publicCollectionDownloadManager.ts
- removed debugging logs added to the download manager and public download manager, blocking rendering.
- removed unnecessarily passing translate util as function parameter
tested locally
> Perf improvements

- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/collectionService.ts
- apps/photos/src/types/collection/index.ts
- apps/photos/src/utils/file/index.ts
- Support for saving collection pubMagicMetadata
- Reflect sort order in the collection view
Tested locally
> Reflect album sort order

- apps/photos/src/pages/shared-albums/index.tsx
- apps/photos/src/services/publicCollectionService.ts
- apps/photos/src/utils/file/index.ts
- PublicLink: Decrypt collection pubMagicMetadata
- PublicLink: Sort collections based on sort property
Tested locally.
- Changed the sort order from mobile, verified that on refresh the web displayed in right order.
> Public link: Sort files based on collection setting

- apps/photos/src/services/migrateThumbnailService.ts
- apps/photos/src/types/file/index.ts
- apps/photos/src/types/upload/index.ts
- Remove unnecessary base interface
- Remove unnecessary type interface
> Remove reduntant interface & type

- apps/photos/src/components/ChangeEmail.tsx
- apps/photos/src/components/Collections/CollectionShare/publicShare/copyLinkModal.tsx
- apps/photos/src/components/Container.ts
- apps/photos/src/components/ExportInProgress.tsx
- apps/photos/src/components/Form/FormContainer.tsx
- apps/photos/src/components/Form/FormPaper/Footer.tsx
- apps/photos/src/components/GalleryEmptyState.tsx
- apps/photos/src/components/MemberSubscriptionManage.tsx
- apps/photos/src/components/SignUp.tsx
- apps/photos/src/components/TwoFactor/Modal/Setup.tsx
- apps/photos/src/components/TwoFactor/Setup.tsx
- apps/photos/src/components/TwoFactor/VerifyForm.tsx
- apps/photos/src/components/TwoFactor/styledComponents.ts
- apps/photos/src/components/WatchFolder/styledComponents.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/manageSubscription/button.tsx
- apps/photos/src/pages/404.tsx
- apps/photos/src/pages/auth/index.tsx
- apps/photos/src/pages/change-email/index.tsx
- apps/photos/src/pages/change-password/index.tsx
- apps/photos/src/pages/credentials/index.tsx
- apps/photos/src/pages/deduplicate/index.tsx
- apps/photos/src/pages/generate/index.tsx
- apps/photos/src/pages/login/index.tsx
- apps/photos/src/pages/recover/index.tsx
- apps/photos/src/pages/shared-albums/index.tsx
- apps/photos/src/pages/two-factor/recover/index.tsx
- apps/photos/src/pages/two-factor/setup/index.tsx
- apps/photos/src/pages/verify/index.tsx
> Removed default export for components/container

- apps/photos/src/services/deduplicationService.ts
- fix an issue where groupByHash added a single file with hash as a separate row, refactored code and fixed the issue by better handling files with hashes and without hashes.
tested locally
> Dedupe fixes

- apps/photos/src/components/Search/SearchBar/searchInput/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/entityService.ts
- apps/photos/src/services/searchService.ts
- apps/photos/src/types/entity.ts
- apps/photos/src/types/search/index.ts
- apps/photos/src/utils/entity.ts
- apps/photos/src/utils/error/index.ts
- apps/photos/src/utils/search/index.ts
- added sync entity logic
- added search by location tag logic
> Location tag search

- apps/photos/src/services/cache/cacheStorageService.ts
-  add conditional logic to ignore logging cache open insecure operation error 
tested locally
> Ignore cache open insecure operation error

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/constants/file.ts
- apps/photos/src/services/electron/ffmpeg.ts
- apps/photos/src/services/ffmpeg/ffmpegFactory.ts
- apps/photos/src/services/ffmpeg/ffmpegService.ts
- apps/photos/src/services/wasm/ffmpeg.ts
- apps/photos/src/types/electron/index.ts
- apps/photos/src/utils/error/index.ts
- apps/photos/src/utils/file/index.ts
- apps/photos/src/utils/photoFrame/index.ts
- apps/photos/src/worker/ffmpeg.worker.ts
- Added support to convert unsupported browser formats for playback
- update FFmpeg to run long-running cmds
- tested command `dontTimeout` option is working correctly.
- convert and play is working properly
> Video playback

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/PhotoViewer/styledComponents/ConversionFailedNotification.tsx
- apps/photos/src/services/updateCreationTimeWithExif.ts
- apps/photos/src/types/Notification/index.tsx
- apps/photos/src/utils/file/index.ts
- remove testing changes added to `getRenderableImage` function
- Fixed Fix time not working with metadata date
- Fixed conversion failed notification position and copy
tested locally
> Fix testing reported issues 

- apps/photos/src/services/collectionService.ts
- apps/photos/src/services/export/index.ts
- apps/photos/src/utils/export/index.ts
- added support to export hidden collection
- converted hidden collection name to `.Hidden`
- tested normal export 
- tested rename 
- tested delete
> Add support to export hidden

- apps/photos/package.json
- yarn.lock
^ title 
- tested build locally
> Upgrade typescript

- package.json
- yarn.lock
^ title 
- tested by building locally
> Upgrade tubrorepo to latest version

- apps/photos/src/components/Collections/CollectionSelector/index.tsx
- fixed handling the case of the uncategorized collection missing, causing upload failure 
tested locally
> Fix first upload to uncategorized collection

- apps/photos/src/constants/collection.ts
> Fix self shared album not shown in collection selector screen 

- apps/photos/src/constants/collection.ts
applying the #1192 patch to main
> [main] patch self shared album not shown in collection screen

- apps/photos/src/components/Collections/CollectionSelector/index.tsx
- apps/photos/src/constants/collection.ts
> Patch release 

- apps/photos/src/components/Chip.tsx
- apps/photos/src/components/PhotoViewer/FileInfo/index.tsx
- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/pages/gallery/index.tsx
Nativation to corresponding album when the  user clicks on the album cards on the bottom of file info sidebar
> Navigation-to-corresponding-album--FileInfo

- apps/photos/package.json
^ title 
building successfully
> moved typescript to dev dependency

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/Upload/UploadProgress/title.tsx
- apps/photos/src/services/upload/uploadManager.ts
- apps/photos/src/services/upload/uploader.ts
- Fix counter not increasing for symlink added / ignored files 
- fixed padding and copy issue 
tested locally
> Fix upload counter issue

- apps/photos/src/constants/upload.ts
- apps/photos/src/services/migrateThumbnailService.ts
- apps/photos/src/services/upload/multiPartUploadService.ts
- apps/photos/src/services/upload/uploadManager.ts
- apps/photos/src/services/upload/uploadService.ts
- apps/photos/src/services/userService.ts
- apps/photos/src/types/user/index.ts
- apps/photos/src/utils/common/apiUtil.ts
- Renabled cf worker for uploading files through cf worker proxy similar to download
> Fix slow uploads

- apps/photos/next.config.js
- apps/photos/public/_headers
> Fixed CORS error [Main]

- apps/photos/next.config.js
- apps/photos/public/_headers
removed coep and coop header from `_header` cf config file 
tested locally with ngrok
> Fixed CORS error 

- apps/photos/src/pages/gallery/index.tsx
- added select +all (cmd/ctrl + a ) keyboard shortcut support 
https://github.com/ente-io/photos-web/assets/46242073/d39ab2e4-6780-45fa-88e2-e396e050afff
- refactored getFilteredData logic  
fixes https://github.com/ente-io/photos-desktop/issues/190
tested locally
> Adds select all shortcut setup

- apps/photos/src/components/pages/gallery/PreviewCard.tsx
- Fix user not found causing shared link to crash 
tested locally
> Fix public link 

- apps/photos/src/components/pages/gallery/PreviewCard.tsx
- apps/photos/src/utils/file/index.ts
> Remove unnecessary useMemo 

- apps/photos/src/components/PhotoViewer/FileInfo/index.tsx
Mapbox shouldn't be shown in the public link
tested locally
> Hide mapbox on public link

- apps/photos/src/components/Collections/CollectionInfoWithOptions.tsx
- apps/photos/src/components/Collections/CollectionListBar/CollectionCard.tsx
- apps/photos/src/components/Collections/CollectionOptions/index.tsx
- apps/photos/src/components/Collections/CollectionSelector/index.tsx
- apps/photos/src/components/Collections/CollectionShare/sharees/index.tsx
- apps/photos/src/components/Collections/CollectionShare/sharees/row.tsx
- apps/photos/src/constants/collection.ts
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/collectionService.ts
- apps/photos/src/types/collection/index.ts
- apps/photos/src/utils/collection/index.ts
- Added support to add to collab album 
tested locally
> Add to collab album support

- .github/workflows/l18n-crowdin.yml
fix crowdin schedule run using `dev` as base and change it to `main`
will be tested tomorrow morning , when the cron runs
> fix sync Crowdin schedule run

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/pages/shared-albums/index.tsx
- apps/photos/src/services/searchService.ts
- added support to show incoming shared files in all section
- added support to search through shared files
- tested that incoming shared files are showed in the all section
- selection works properly
- in PhotoVeiwer view has correct options
> Show incoming shared files in ALL section 

- apps/photos/src/components/Collections/CollectionOptions/AlbumCollectionOption.tsx
- apps/photos/src/components/Collections/CollectionOptions/SharedCollectionOption.tsx
- apps/photos/src/components/Collections/CollectionOptions/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/collectionService.ts
- apps/photos/src/types/collection/index.ts
- apps/photos/src/utils/collection/index.ts
- apps/photos/src/utils/file/index.ts
- apps/photos/src/utils/magicMetadata/index.ts
- Added option to archive and unarchive shared albums
- Added support to hide archived shared album files from all section
- tested archiving and unarchiving collection and saw they are hidden properly from the all section gallery
> Add support to archive shared album

- apps/photos/src/utils/billing/index.ts
- apps/photos/tsconfig.json
Gradually migrating code to stricter typescript rules 
tested builds successfully
> Enable stricter typescript

- apps/photos/package.json
- yarn.lock
^ title 
not used anywhere
building without any issue
> remove http-proxy-middleware

- apps/photos/src/services/collectionService.ts
> Handle reset for cover photos

- apps/photos/src/components/Collections/CollectionShare/index.tsx
- apps/photos/src/components/pages/gallery/SelectedFileOptions.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/collectionService.ts
- apps/photos/src/utils/file/index.ts
^ title 
- this also fixes an issue where trying to delete files when shared files were selected was failing, before we were not ignoring the files properly 
tested all the touched functions
> Refactored selectedFileOptions utils to file util

- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/entityService.ts
- apps/photos/src/services/searchService.ts
add search-related logs for debugging user location tag search issue 
tested locally
> Add search logs

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/PhotoList.tsx
- apps/photos/src/pages/shared-albums/index.tsx
- apps/photos/src/services/publicCollectionService.ts
- apps/photos/src/themes/components.ts
- apps/photos/src/types/publicCollection/index.ts
- apps/photos/src/utils/publicCollectionGallery/index.ts
> Show referral code on public link

- apps/photos/src/components/Login.tsx
- apps/photos/src/services/userService.ts
- apps/photos/src/types/user/index.ts
Verified that login works fine when MFA is enabled or disabled.
> Honor email mfa setting

- apps/photos/src/components/pages/gallery/SelectedFileOptions.tsx
> Add delete option to search mode

- apps/photos/src/components/Upload/Uploader.tsx
- apps/photos/src/pages/gallery/index.tsx
^title
tested drag and drop in various scenarios 
- all section
- an active collection
- trash 
- hidden section
- uncategorized
- public collection
> upload to active collection on drag and drop

- apps/photos/src/components/Collections/styledComponents.ts
- apps/photos/src/components/PhotoList.tsx
- updated referral banner style
- fix unable to copy referral code 
tested locally
> Style referral banner

- apps/photos/src/components/PhotoList.tsx
- updated the album footer row height in case it has a referral code banner 
tested locally
> Remove unnecessary scroll on albums page

- apps/photos/src/services/authenticator/authenticatorService.ts
- apps/photos/src/types/authenticator/code.ts
- Fixed filtering logic for null auth codes.
- Fixed comparison that was resulting in exception -> null auth code.
Tested locally
> Fix issues in rendering auth codes

- apps/photos/src/pages/auth/index.tsx
> Auth: restrict max-width to limit 2 columns

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/Collections/CollectionShare/publicShare/manage/deviceLimit.tsx
- apps/photos/src/utils/collection/index.ts
> Add support for no device limit on links

- apps/photos/src/utils/export/index.ts
^ title 
- tested existing exported will be properly renamed to a newer format
> Remove dot prefix from hidden collection export names

- apps/photos/src/components/VerifyMasterPasswordForm.tsx
- apps/photos/src/pages/credentials/index.tsx
- apps/photos/src/utils/crypto/libsodium.ts
- apps/photos/src/utils/error/index.ts
- apps/photos/src/utils/storage/sessionStorage.ts
- apps/photos/src/worker/crypto.worker.ts
- fixed issue with login when two-factor was setup with srp enabled 
tested locally
> Fix login v2 issues

- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/utils/file/index.ts
- Fixed individual hide not hiding the file from all albums
- Fixed hidden item section not showing archived hidden files 
tested locally
> Fix hidden section issues

- apps/photos/src/components/ItemList.tsx
Fixed issue with the caller expecting the generateItemKey 
to be `generateItemKey: (item: any) => string;`
but it was actually `generateItemKey: (index: number, itemData:ItemData) => string;`
and hence returned undefined as the key 
added proper types and added helper `getItemKey`  which passed the item to generateItemKey matching caller expectation
tested locally, react warning is gone
> Fix missing react key warning

- apps/photos/src/components/Collections/CollectionShare/publicShare/manage/index.tsx
- apps/photos/src/components/PhotoList.tsx
- apps/photos/src/components/PhotoViewer/FileInfo/RenderCaption.tsx
- apps/photos/src/constants/collection.ts
- apps/photos/src/pages/credentials/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/export/index.ts
- apps/photos/src/utils/collection/index.ts
- apps/photos/src/utils/export/index.ts
- fixed edit description option shown for shared-album on albums domain and hide the description box if the description is empty and the file is shared.
- fixed link icon not updated when public link removed 
- Fixed shaking screen issue
tested locally
> UI issues fixes

- apps/photos/src/components/Login.tsx
- apps/photos/src/pages/credentials/index.tsx
- apps/photos/src/services/userService.ts
- apps/photos/src/utils/storage/index.ts
- apps/photos/src/utils/storage/localStorage.ts
- SrpAttributes was getting used even when we had key attributes locally 
That along with the srpAttribute not updating when the password was changed was causing the issue
- also fixed the issue of the SRP setup attempted when srpAttribites already set 
tested locally
> Fix login issue on password change 

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/PhotoList.tsx
- apps/photos/src/components/Search/SearchBar/searchInput/index.tsx
- apps/photos/src/pages/credentials/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/searchService.ts
- apps/photos/src/types/search/index.ts
-  Added support to search types 
- tested locally for all types
> Type search

- apps/photos/src/components/CaptionedText.tsx
- apps/photos/src/components/Collections/CollectionShare/emailShare/ManageParticipant.tsx
- apps/photos/src/components/Collections/CollectionShare/publicShare/manage/linkExpiry.tsx
- apps/photos/src/components/Collections/CollectionShare/publicShare/managePublicShare.tsx
- apps/photos/src/components/Menu/EnteMenuItem.tsx
- apps/photos/src/themes/components.ts
- apps/photos/src/themes/types.ts
- Update to Figma design, reflect link expired state
tested locally
> Handle link expired state

- apps/photos/src/components/Form/ShowHidePassword.tsx
> Don't tab focus on show password option in input field 

- apps/photos/src/components/Collections/CollectionShare/publicShare/EnablePublicShareOptions.tsx
> update collect photo link create option icon

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/utils/photoFrame/index.ts
- removed `photoViewer`  specific state from parent and  handled them internally in the component 
- tested the state change are properly handled
> Refactor photoViewer 

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/services/downloadManager.ts
- apps/photos/src/utils/file/index.ts
- handle cases where the  response doesn't have content length, and show infinite loader for them
- Disable convert and play on web
tested locally
> Fix download progress

- apps/photos/src/constants/file.ts
added missing supported formats `tif` and `arw`
tested locally
> add missing supported types

- apps/photos/src/utils/time/format.ts
made date format declared outside the function to avoid creating them each call 
- confirmed by laurens, fixes his crash issue 
- confirmed doesn't cause any issue with crypto or ml worker
> Fix OOM crashes 

- apps/photos/src/services/userService.ts
- apps/photos/src/utils/common/apiUtil.ts
- add an option to override CF proxy in dev environment for testing
tested locally
> option to override disableCFUploadProxy

- apps/photos/src/services/entityService.ts
- apps/photos/src/types/entity.ts
-  fix entity diff sync response type, remove `hasMore`  
tested locally
> Fix entity diff sync

- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/styles/global.css
fixes #1388
- updated the icons and fixed the misalignment issue
tested locally
> Fix misaligned icons

- apps/photos/src/services/upload/livePhotoService.ts
> LivePhotoCluster: Handle _HVEC suffix

- apps/photos/src/services/livePhotoService.ts
- apps/photos/src/services/upload/livePhotoService.ts
- apps/photos/src/utils/file/index.ts
handle motion-photo assets with names, image: `PXL_123.mov.jpeg` and video `PXL_123.mov`
- tested with updated upload test dataset including new sample.
> Handle new motion photo image name format

- apps/photos/src/pages/_app.tsx
- apps/photos/src/services/HTTPService.ts
- apps/photos/src/services/upload/multiPartUploadService.ts
- apps/photos/src/services/upload/uploadService.ts
- apps/photos/src/services/upload/uploader.ts
- apps/photos/src/types/upload/index.ts
- apps/photos/src/utils/sentry/index.ts
> Add logs for gif upload issue debugging

- apps/photos/src/components/Login.tsx
- apps/photos/src/components/SignUp.tsx
- apps/photos/src/pages/deduplicate/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/pages/two-factor/recover/index.tsx
- apps/photos/src/pages/two-factor/verify/index.tsx
- apps/photos/src/pages/verify/index.tsx
- apps/photos/src/services/HTTPService.ts
- apps/photos/src/services/authenticator/authenticatorService.ts
- apps/photos/src/services/userService.ts
- apps/photos/src/utils/error/index.ts
- apps/photos/src/utils/sentry/index.ts
- improved logging and handling of network errors
tested locally
> Cleanup error messages

- apps/photos/src/utils/file/livePhoto.ts
- update VIDEO_EXTENSIONS list
tested locally
> fix motion photo clustering issue 

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/Sidebar/AdvancedSettings.tsx
- apps/photos/src/components/Sidebar/Preferences/index.tsx
- apps/photos/src/components/Upload/Uploader.tsx
- apps/photos/src/pages/_app.tsx
- apps/photos/src/services/upload/uploadManager.ts
- apps/photos/src/utils/storage/localStorage.ts
> Add option to locally disable cf proxy

- apps/photos/src/pages/credentials/index.tsx
- apps/photos/src/services/userService.ts
> Fix initial load warning not shown on srp login without 2fa

- apps/photos/src/services/export/index.ts
- apps/photos/src/utils/file/index.ts
fix non-owner collection, self-added files export falling 
tested locally
> Fix export issue

- apps/photos/src/components/Sidebar/SubscriptionStatus/index.tsx
- apps/photos/src/types/user/index.ts
- apps/photos/src/utils/billing/index.ts
> Hide free trial expiry if ADD_ON is active

- apps/photos/src/services/upload/fileService.ts
- apps/photos/src/services/upload/metadataService.ts
- apps/photos/src/services/upload/uploadManager.ts
- use file names to map files with JSON during Google Photo import 
tested locally and updated sample dataset
> update google json matching logic

- apps/photos/src/services/upload/fileService.ts
- apps/photos/src/services/upload/metadataService.ts
- apps/photos/tests/upload.test.ts
- Fixed the getMetadataJSONMapKeyForJSON using an array instead of the first index 
- add test for JSON matching 
- Refactor som code 
tested locally
> fix google json matching tests

- apps/auth/sentry.client.config.ts
> update auth sentry dsn

- apps/auth/sentry.client.config.ts
> Release auth dsn update

- packages/shared/next/utils/sentry.js
- packages/shared/sentry/utils.ts
- fix sentry logging was getting activated in dev environment 
tested locally
> Update is sentry enabled check

- apps/photos/src/services/searchService.ts
> Move magic to first

- apps/photos/public/locales/en/translation.json
- apps/photos/src/components/Sidebar/SubscriptionStatus/index.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/card/free.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/card/index.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/card/paid.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/manageSubscription/index.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/plans/BfAddOnRow.tsx
- apps/photos/src/components/pages/gallery/PlanSelector/plans/index.tsx
> Show ADD_ON details + update subscription related msg

- apps/photos/src/services/embeddingService.ts
- apps/photos/src/utils/embedding.ts
- packages/shared/error/index.ts
Complete embedding sync was getting blocked due to some file sync error, 
Made sync continue regardless of the file sync issue, and added logging to know if the user has hidden albums
tested locally
> Fix embedding sync blocked

- apps/photos/src/constants/upload.ts
> Add mov to whitelisted file formats

- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/clipService.ts
- apps/photos/src/services/searchService.ts
- packages/shared/error/index.ts
> Add support to detect unsupported platform and stop trying to run clip

- apps/auth/src/components/OTPDisplay.tsx
- current 
- fixed 
tested locally
> Fix OTP display ui issue

- .husky/pre-commit
- dev QoL improvement 
tested locally
> Prevent from directly committing on main locally

- apps/photos/src/services/clipService.ts
- apps/photos/src/services/searchService.ts
- improve handling of clip search failure but to prevent complete search failure
tested locally
> handle Clip search failure issue

- apps/photos/src/components/PhotoViewer/index.tsx
> Remove zoom option from videos

- apps/photos/src/pages/index.tsx
- packages/accounts/pages/credentials.tsx
> avoid uncaught error during login due to getEncryptionKey

- apps/photos/src/components/Sidebar/UtilitySection.tsx
- packages/shared/constants/pages.tsx
> Remove authenticator option from photos sidebar

- apps/photos/public/locales/en/translation.json
- packages/accounts/api/user.ts
- packages/accounts/components/SignUp.tsx
- packages/accounts/pages/verify.tsx
- packages/shared/storage/localStorage/helpers.ts
- packages/shared/storage/localStorage/index.ts
> Add referral - sign-up form  

- apps/photos/tests/upload.test.ts
- packages/shared/time/index.ts
- reject date parsed from the name if it's less than 1990  
- added test
> Fix file name date time parsing

- apps/photos/src/utils/billing/index.ts
Include storageBonus in the calculation
> Fix: include bonus in storage quota check

- apps/photos/src/pages/deduplicate/index.tsx
- packages/shared/crypto/helpers.ts
> remove prod console.log

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/components/PhotoViewer/index.tsx
- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/services/download/index.ts
- apps/photos/src/types/file/index.ts
- apps/photos/src/utils/file/index.ts
- apps/photos/src/utils/photoFrame/index.ts
don't block on video conversion to show the full res image in live photo 
tested locally
> Add segmented live photo loading

- apps/photos/src/services/download/index.ts
- apps/photos/src/services/machineLearning/mlWorkManager.ts
- packages/shared/worker/comlinkWorker.ts
- fix logging inside worker in electron 
- added more logs to debug the ML issue 
tested locally
> Add ML logging

- apps/photos/src/services/download/index.ts
- fix fileCache put attempted on the web
> Fix testing issues

- apps/photos/src/components/Sidebar/AdvancedSettings.tsx
- apps/photos/src/components/Sidebar/Preferences/index.tsx
> Move cache folder configuration option to Advanced section

- apps/photos/src/services/download/index.ts
- fixed get cached throwing error for image, when is missing 
tested locally
> Fix file cache load issue

- apps/photos/src/components/MachineLearning/ImageViews.tsx
- apps/photos/src/components/MachineLearning/PeopleList.tsx
- apps/photos/src/services/machineLearning/faceService.ts
- apps/photos/src/services/machineLearning/machineLearningService.ts
- apps/photos/src/utils/storage/mlIDbStorage.ts
- apps/photos/src/worker/ml.worker.ts
- packages/shared/storage/cacheStorage/helpers.ts
Add face crop regeneration logic triggered if file is missing from cache 
tested locally
> Regenerate face crops

- apps/photos/src/components/PhotoViewer/ImageEditorOverlay/index.tsx
fix broken state set logic
tested locally
> fix editor issue 

- apps/photos/src/components/Sidebar/AdvancedSettings.tsx
- fix custom directory option shown on web
- fix indexing status shown on web
tested locally
> Remove Desktop only settings from web 

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
> Added vscode settings file for code auto format

- .vscode/settings.json
~ signed off by aakanksha0407@gmail.com
Changed vscode setting to auto format code.
fixes #1525
> VSCode ESLint Integration

- packages/shared/electron/service.ts
- packages/shared/electron/worker/client.ts
- packages/shared/logging/index.ts
fix logging not working inside worker 
tested locally and with Jishnu
> fix logging inside worker

- packages/shared/electron/service.ts
- packages/shared/electron/worker/client.ts
- packages/shared/logging/index.ts
> Fix ml not starting issue 

- packages/accounts/pages/credentials.tsx
> [credential page] Fix redirect logic on successful login  

- apps/auth/src/pages/auth/index.tsx
- fix pages import 
tested build locally
> Fix auth page build

- .vscode/settings.json
fixes the warning shown in `settings.json` 
> Auto Fix is enabled by default. Use the single-string form. (2)
tested locally
> improve vscode setting.json

- packages/shared/hooks/useLocalState.tsx
fixes #307
^ title 
tested locally
> Fix collection sort state not preserved 

- apps/photos/src/pages/_app.tsx
> fix missing await

- apps/photos/src/components/Search/SearchBar/searchInput/index.tsx
- apps/photos/src/services/searchService.ts
> Remove debug logs

- apps/photos/src/services/deduplicationService.ts
> Sort dedupe size descending

- apps/photos/src/components/Collections/CollectionSelector/index.tsx
> fix add to album screen padding issue

- apps/photos/src/components/PhotoViewer/index.tsx
Fix using arrow keys to move in input field causes `photoViewer` file change
tested locally
> Fix keyboard navigation issue

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/components/pages/sharedAlbum/SelectedFileOptions.tsx
- apps/photos/src/pages/shared-albums/index.tsx
^ title 
tested locally and with jishnu
> Add select functionality to shared albums

- apps/photos/src/services/clipService.ts
- apps/photos/src/services/upload/uploadManager.ts
- prevent non-jpeg from getting processed for clip extraction during local file extraction 
tested locally
> Fix SOI not found error

- apps/photos/src/pages/gallery/index.tsx
> Hide hidden collection files from all section

- apps/photos/src/pages/gallery/index.tsx
- apps/photos/src/pages/shared-albums/index.tsx
> Remove debugging log

- apps/photos/src/components/PhotoFrame.tsx
- apps/photos/src/utils/photoFrame/index.ts
^ title 
fixes #1589
tested locally
> Remove download option from video player control list of shared link if download disabled

- apps/photos/src/components/Collections/CollectionShare/emailShare/AddParticipant.tsx
- apps/photos/src/components/Collections/CollectionShare/emailShare/AddParticipantForm.tsx
- fix share dialog closing on error 
> Fix error handling in share dialog

- apps/photos/src/pages/deduplicate/index.tsx
The list of photos shown on the dedup screen did not update if we selected a subset of the duplicates and deleted them. This is because while we're issuing a remote API request, we don't seem to be updating our local storage with the results of that when we're on this screen. So when the gallery on this screen re-renders, it still reads the same files again, even after they've been deleted.
Not happy with the current solution, but it does solve the customers issue. Have added an "Enhancement" tag to flag this.
I was able to reproduce the issue. After making these changes, I don't see it anymore. Haven't done exhaustive checks, but it fixes the happy path at least.
Tested locally.
> Update the UI when deleting a subset of the duplicates

- apps/auth/sentry.client.config.ts
- apps/photos/sentry.client.config.ts
- packages/shared/apps/env.ts
- packages/shared/network/api.ts
- packages/shared/sentry/config/sentry.config.base.ts
- turbo.json
Inline a bunch of code that deals with flexibility that we're not currently using. The intent is to simplify sentry configuration to a few lines. More can be done on this, this is a start.
> Reduce Sentry noise

- scripts/deploy.sh
This allows us to perform test deployments of any of the supported apps.
Refs:
- https://bash.cyberciti.biz/guide/The_case_statement
- https://stackoverflow.com/questions/2172352/in-bash-how-can-i-check-if-a-string-begins-with-some-value
> Prefix match the branch name to decide what app to build

- apps/accounts/src/pages/_app.tsx
- apps/accounts/src/pages/passkeys/index.tsx
- Add a page title
- Reset the form on submit
For the second one, I just did a smoke test by commenting out the surrounding code, did not do an actual test.
> Accounts UI tweaks

- docs/New.md
Documentation only, no code changes.
> Add a small (generic workflow) getting started doc

- apps/auth/src/pages/auth/index.tsx
Fixes https://github.com/ente-io/auth/issues/462
> Remove dangling semicolon

- docs/dev.md
> docs: Mention aliases

- apps/photos/.env.development
- apps/photos/.env.localhost
- apps/photos/package.json
- package.json
- packages/shared/network/api.ts
Also, rename the environment variable to match what one would naturally type.
> Clarify a few things around running shared albums locally

- crowdin.yml
> Fix the source file used by Crowdin
